import pandas as pd
import os

def generate_cost_model():
    print("=== Phase 8: Generating FireAgent Cost Model ===")
    
    # ----------------------------------------
    # Provider Pricing Rates (Current as of 2024)
    # ----------------------------------------
    stt_rate_per_min = 0.0043      # Deepgram Nova-2 Pay-As-You-Go
    tts_rate_per_1k_char = 0.15    # ElevenLabs Creator tier approx
    llm_input_1m = 0.150           # GPT-4o-mini Input Tokens ($0.15 per 1M)
    llm_output_1m = 0.600          # GPT-4o-mini Output Tokens ($0.60 per 1M)
    twilio_rate_per_min = 0.013    # Twilio Programmable Voice (Outbound)
    
    # ----------------------------------------
    # Assumptions for a typical FireReach SDR Call
    # ----------------------------------------
    avg_call_duration_min = 3
    avg_chars_spoken_by_ai = 1800  # AI speaks about ~300 words
    avg_tokens_input = 2500        # System prompt + transcript history per call
    avg_tokens_output = 400        # Total tokens generated by AI
    
    # ----------------------------------------
    # Per-Call Calculations
    # ----------------------------------------
    stt_cost_per_call = avg_call_duration_min * stt_rate_per_min
    tts_cost_per_call = (avg_chars_spoken_by_ai / 1000) * tts_rate_per_1k_char
    llm_cost_per_call = (avg_tokens_input / 1000000) * llm_input_1m + (avg_tokens_output / 1000000) * llm_output_1m
    telephony_cost_per_call = avg_call_duration_min * twilio_rate_per_min
    
    total_cost_per_call = stt_cost_per_call + tts_cost_per_call + llm_cost_per_call + telephony_cost_per_call
    
    # ----------------------------------------
    # Volume Projection
    # ----------------------------------------
    data = []
    volumes = [100, 1000, 5000, 10000, 50000]
    
    for v in volumes:
        data.append({
            "Monthly Calls": v,
            "STT Cost ($)": round(stt_cost_per_call * v, 2),
            "LLM Cost ($)": round(llm_cost_per_call * v, 2),
            "TTS Cost ($)": round(tts_cost_per_call * v, 2),
            "Telephony Cost ($)": round(telephony_cost_per_call * v, 2),
            "Grand Total Spend ($)": round(total_cost_per_call * v, 2),
            "Avg Cost Per Call ($)": round(total_cost_per_call, 3)
        })
        
    df = pd.DataFrame(data)
    csv_file = os.path.join(os.path.dirname(__file__), "fireagent_cost_model.csv")
    df.to_csv(csv_file, index=False)
    
    print(f"\n✅ Generated projection spreadsheet at: {csv_file}")
    
    print("\n📊 Cost Breakdown for a typical 3-minute Outbound SDR Call:")
    print(f"   - Telephony (Twilio):  ${telephony_cost_per_call:.4f} ({(telephony_cost_per_call/total_cost_per_call)*100:.1f}%)")
    print(f"   - STT (Deepgram):      ${stt_cost_per_call:.4f} ({(stt_cost_per_call/total_cost_per_call)*100:.1f}%)")
    print(f"   - LLM (GPT-4o-mini):   ${llm_cost_per_call:.4f} ({(llm_cost_per_call/total_cost_per_call)*100:.1f}%)")
    print(f"   - TTS (ElevenLabs):    ${tts_cost_per_call:.4f} ({(tts_cost_per_call/total_cost_per_call)*100:.1f}%)")
    print(f"   ----------------------------------------")
    print(f"   TOTAL COST PER CALL:   ${total_cost_per_call:.4f}")
    
    print("\n💡 Optimization Insight: TTS is always your biggest expense. Switching ElevenLabs to Deepgram Aura or Cartesia can cut total call costs by up to 50%.")

if __name__ == "__main__":
    generate_cost_model()
