import re

html_path = "/Users/bhoomim/devops CI:CD/handbook/ai_agents_observability.html"
with open(html_path, "r") as f:
    content = f.read()

t5_to_t7 = """
  t5: {
    tag:'Core Concept · AI Fundamentals', num:5, title:'Perception & Tool Execution', desc:'How agents interact with the outside world through tools, APIs, and sensors.',
    theory:`<div class="card"><h3>👀 Perception & 🛠️ Execution</h3><p>An agent is useless if it cannot see or change the world. This is achieved via <strong>Tools (Actuators)</strong> and <strong>Sensors (Perception)</strong>.</p><h4>1. Perception (Sensors)</h4><p>Agents perceive the world by receiving data. This data is converted into text and added to the context window.</p><ul><li><strong>Webhooks</strong>: Receiving an email, Slack message, or Github PR event.</li><li><strong>Polling</strong>: Checking an API every 5 minutes.</li><li><strong>User Input</strong>: A user typing a message in a chat interface.</li></ul><h4>2. Execution (Actuators/Tools)</h4><p>When the LLM decides to take action, it outputs a tool name and JSON arguments. The execution layer runs the actual code.</p><div class="cb"><span class="ck">def</span> <span class="cv">execute_tool</span>(name, args):
    <span class="ck">if</span> name == <span class="cs">"search_web"</span>:
        <span class="ck">return</span> tavily.search(args[<span class="cs">"query"</span>])
    <span class="ck">elif</span> name == <span class="cs">"send_email"</span>:
        <span class="ck">return</span> smtp.send(args[<span class="cs">"to"</span>], args[<span class="cs">"body"</span>])
    <span class="ck">else</span>:
        <span class="ck">return</span> <span class="cs">"Error: Unknown tool"</span></div></div>`,
    mcqs:[
      {q:"What is the primary purpose of Perception in an agent?",opts:["A. To generate text","B. To store memory","C. To ingest external data into the context window","D. To execute code"],ans:2,exp:"Perception converts external events into text the LLM can reason over."},
      {q:"Which of these is a 'Sensor' for an agent?",opts:["A. A Python script that sends an email","B. A webhook receiving a GitHub issue creation event","C. A SQL DELETE statement","D. The LLM reasoning engine"],ans:1,exp:"A webhook provides data to the agent, acting as a sensor."},
      {q:"Which of these is an 'Actuator' (Tool) for an agent?",opts:["A. A webhook receiving an event","B. The user typing a message","C. An API call that creates a Jira ticket","D. The short-term memory"],ans:2,exp:"Creating a ticket changes the external environment, acting as an actuator."},
      {q:"When an LLM decides to use a tool, what does it actually output?",opts:["A. A Python binary","B. A JSON object with the tool name and arguments","C. A SQL database","D. A bash script"],ans:1,exp:"LLMs output structured text (usually JSON) which the execution layer parses."},
      {q:"Who executes the actual tool code (e.g., making the HTTP request)?",opts:["A. The LLM directly on OpenAI's servers","B. The Agent's local execution layer (Python/Node code)","C. The vector database","D. The user"],ans:1,exp:"The LLM only generates the JSON. Your code (the execution layer) must actually run the tool."},
      {q:"What happens if a tool execution fails (e.g., API 404)?",opts:["A. The agent crashes immediately","B. The error is added to memory and the LLM is prompted to retry or adapt","C. The LLM automatically fixes the API","D. The agent restarts the computer"],ans:1,exp:"Errors are fed back to the LLM as observations so it can reason about the failure."},
      {q:"Why is JSON Schema used for tool definitions?",opts:["A. Because it's faster than XML","B. To enforce strict type definitions and descriptions for the LLM to understand how to use the tool","C. To encrypt the data","D. Because Python requires it"],ans:1,exp:"JSON Schema describes the exact structure of the arguments the tool expects."},
      {q:"A 'polling' sensor works by:",opts:["A. Waiting for the user to type","B. Repeatedly checking an API or DB at intervals to see if there is new data","C. Receiving webhooks","D. Sending emails"],ans:1,exp:"Polling proactively asks 'is there new data?' on a schedule."},
      {q:"What is the risk of giving an agent a 'delete_database' tool?",opts:["A. The agent might use it accidentally if the reasoning goes wrong","B. It takes too much memory","C. It slows down the LLM","D. There is no risk"],ans:0,exp:"Agents can hallucinate or misinterpret goals, leading to destructive actions if given dangerous tools."},
      {q:"How do you prevent an agent from taking dangerous actions?",opts:["A. Don't use LLMs","B. Use Human-in-the-Loop (HITL) approval before executing dangerous tools","C. Make the prompt very long","D. Use a vector database"],ans:1,exp:"HITL pauses execution and asks a human to approve the tool call."},
      {q:"If an agent has 100 tools, what is a common problem?",opts:["A. The LLM gets confused and context window fills up with tool schemas","B. The agent gets too smart","C. It runs out of RAM","D. The tools execute simultaneously"],ans:0,exp:"Too many tools in the context window degrades reasoning quality and increases costs."},
      {q:"How can you solve the 'too many tools' problem?",opts:["A. Delete all tools","B. Use Tool Retrieval (RAG for tools) to only inject relevant tools into the context","C. Increase the temperature","D. Use GPT-2"],ans:1,exp:"Tool Retrieval dynamically selects which tools to give the LLM based on the current goal."},
      {q:"When a tool returns 10,000 lines of JSON, what should the execution layer do?",opts:["A. Send it all to the LLM","B. Crash","C. Filter, truncate, or summarize the JSON before sending it to the LLM to save context","D. Convert it to XML"],ans:2,exp:"Massive tool outputs blow up the context window. They must be filtered."},
      {q:"An agent that trades stocks based on Twitter sentiment uses Twitter as a: ",opts:["A. Actuator","B. Sensor","C. Memory","D. Output"],ans:1,exp:"Twitter provides the input data (sensor)."},
      {q:"The stock trading agent uses a broker API to buy shares. The broker API is a:",opts:["A. Sensor","B. Actuator (Tool)","C. Memory","D. Perception"],ans:1,exp:"The broker API changes the world (buying shares), making it an actuator."}
    ],
    flows:[
      {title:"Tool Execution",items:["start:LLM Outputs JSON","proc:Parse JSON","proc:Validate Arguments","proc:Run Python Function","end:Return Result String"]},
      {title:"Error Handling",items:["start:Function Throws Error","proc:Catch Exception","proc:Format as 'Error: X'","proc:Append to Memory","end:Ask LLM to retry"]},
      {title:"Human-in-the-Loop",items:["start:LLM Decides Action","dec:Is Tool Dangerous?","proc:Pause Agent","proc:Request User Approval","end:Execute if Approved"]}
    ],
    game:{icon:"👀",title:"Tool Smith",desc:"Master perception and execution",badges:["👀 Watcher","🛠️ Blacksmith","🛡️ Guardian"],challenges:[{icon:"🛠️",title:"Build a Tool",desc:"Write a JSON schema for a weather tool",xp:50},{icon:"🛡️",title:"Add Safety",desc:"Implement a HITL check in code",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 12+ on MCQs",xp:100}]},
    project:{title:"Safe Tool Executor",badge:"Executor",desc:"Build an execution layer that validates JSON arguments and catches errors.",tags:["Python","Safety"],steps:[{title:"Define Tool",desc:"Create a dummy function"},{title:"JSON parsing",desc:"Parse LLM output safely with try/except"},{title:"Validation",desc:"Check if required args exist"},{title:"Error return",desc:"Return error string instead of crashing"}],code:`import json\n\ndef my_tool(x):\n    if x < 0: raise ValueError("Negative not allowed")\n    return x * 2\n\ndef execute_llm_call(llm_json_string):\n    try:\n        call = json.loads(llm_json_string)\n        if call["name"] == "my_tool":\n            if "x" not in call["args"]:\n                return "Error: Missing required argument 'x'"\n            return str(my_tool(call["args"]["x"]))\n    except json.JSONDecodeError:\n        return "Error: LLM output was not valid JSON"\n    except Exception as e:\n        return f"Error executing tool: {str(e)}"`}
  },
  t6: {
    tag:'Core Concept · AI Fundamentals', num:6, title:'System Prompts for Agents', desc:'How to write robust, multi-part system prompts that guide autonomous behavior.',
    theory:`<div class="card"><h3>📜 Anatomy of an Agent Prompt</h3><p>An agent's system prompt is much more complex than a chatbot's. It must define the persona, the available tools, the memory constraints, and the exact output format (like ReAct).</p><h4>The 5-Part Agent Prompt</h4><ol><li><strong>Persona &amp; Role</strong>: "You are a senior DevOps engineer..."</li><li><strong>Goal &amp; Context</strong>: "Your goal is to deploy the app. The environment is AWS."</li><li><strong>Rules &amp; Constraints</strong>: "Never delete a database. Always verify before restarting."</li><li><strong>Tool Descriptions</strong>: (Often injected automatically by the API)</li><li><strong>Output Format</strong>: "You must respond using the exact format: THOUGHT: ... ACTION: ..."</li></ol><div class="box b-ro"><h5>⚠️ Prompt Drift</h5><p>As context grows, LLMs often forget instructions at the beginning of the prompt (Lost in the Middle). Constantly repeating critical rules near the end of the prompt can help.</p></div></div>`,
    mcqs:[
      {q:"Why is an agent prompt usually longer than a chatbot prompt?",opts:["A. To waste tokens","B. Because it must define rules, output formats, tool usage, and complex constraints","C. Because LLMs need at least 1000 words to work","D. To slow down execution"],ans:1,exp:"Agents need strict boundaries and formatting rules to function autonomously."},
      {q:"What is 'Prompt Drift' (Lost in the Middle)?",opts:["A. The LLM changes its name","B. The LLM forgets instructions placed in the middle of a very long context window","C. The user forgets what they asked","D. The API connection drops"],ans:1,exp:"LLMs pay more attention to the very beginning and very end of a prompt."},
      {q:"Which is a good constraint to put in an agent prompt?",opts:["A. 'Do whatever you want'","B. 'Always verify the syntax before running the execute_sql tool'","C. 'Be a good AI'","D. 'Write a poem'"],ans:1,exp:"Constraints should be specific and actionable, relating to dangerous tools."},
      {q:"If an agent keeps outputting plain text instead of the required JSON, what part of the prompt needs fixing?",opts:["A. Persona","B. Goal","C. Output Format / Formatting Instructions","D. Context"],ans:2,exp:"The Output Format section strictly dictates how the LLM should structure its response."},
      {q:"In the ReAct pattern, the prompt forces the LLM to output:",opts:["A. Only the final answer","B. THOUGHT, then ACTION, then wait for OBSERVATION","C. Python code","D. A SQL table"],ans:1,exp:"ReAct prompts strictly enforce the Thought -> Action -> Observation loop format."},
      {q:"Should you hardcode the current date in the system prompt?",opts:["A. Yes, forever","B. No, it should be dynamically injected as context when the agent starts","C. Yes, LLMs can't read dates","D. No, dates don't matter"],ans:1,exp:"Dynamic context (date, user name, environment) should be injected programmatically."},
      {q:"What is the 'Persona' part of the prompt?",opts:["A. The API key","B. Setting the role and tone (e.g., 'You are a strict security auditor')","C. The JSON schema","D. The memory array"],ans:1,exp:"Persona helps guide the LLM's reasoning style and stylistic choices."},
      {q:"If you tell an agent 'Never do X', and it still does X, a good workaround is to:",opts:["A. Tell it 'Never ever do X'","B. Provide positive instructions: 'Instead of X, always do Y'","C. Delete the prompt","D. Increase temperature"],ans:1,exp:"LLMs often struggle with negative constraints. Positive alternatives work better."},
      {q:"Where is the best place to put the most critical safety rule in a long prompt?",opts:["A. At the very beginning","B. In the middle","C. At the very end (closest to the user input)","D. In a separate file"],ans:2,exp:"Due to recency bias, LLMs pay the most attention to the text at the very end of the prompt."},
      {q:"When using OpenAI's Function Calling, do you need to manually write tool descriptions in the text prompt?",opts:["A. Yes, always","B. No, they are passed in a separate structured 'tools' array in the API call","C. Only for Python tools","D. Yes, in XML"],ans:1,exp:"Modern APIs separate the text prompt from the structured tools array."},
      {q:"Which of these is dynamic context?",opts:["A. 'You are a helpful assistant'","B. 'The user's current OS is MacOS'","C. 'Always use JSON'","D. 'Never delete files'"],ans:1,exp:"Dynamic context changes based on the user or environment at runtime."},
      {q:"A prompt that includes examples of successful executions is using:",opts:["A. Zero-shot prompting","B. Few-shot prompting","C. Chain of Thought","D. Fine-tuning"],ans:1,exp:"Few-shot prompting provides examples to show the LLM exactly what to do."},
      {q:"If an agent is failing a complex task, what prompt technique helps?",opts:["A. 'Think step-by-step' (Chain of Thought)","B. 'Output only JSON'","C. 'Be brief'","D. 'Speak in Spanish'"],ans:0,exp:"CoT forces the LLM to spend tokens reasoning before acting, improving accuracy."},
      {q:"What is a meta-prompt?",opts:["A. A prompt about Facebook","B. A prompt used to generate or optimize other prompts","C. A very short prompt","D. An empty prompt"],ans:1,exp:"Meta-prompts instruct an LLM to write a system prompt for another agent."},
      {q:"Why should prompts be version controlled (e.g., in Git)?",opts:["A. They shouldn't be","B. Because changing a word can drastically alter agent behavior, treating prompts as code is best practice","C. Because GitHub requires it","D. To save disk space"],ans:1,exp:"Prompts are essentially the 'source code' of the agent's logic."}
    ],
    flows:[
      {title:"Prompt Construction",items:["start:Base Persona","proc:Inject Dynamic Context","proc:Inject Rules","proc:Inject Tool Schemas","end:Final System Prompt"]},
      {title:"Few-Shot Injection",items:["start:User Goal","proc:Find Similar Past Successes","proc:Format as Examples","proc:Add to Prompt","end:Send to LLM"]},
      {title:"Recency Bias Fix",items:["start:Build Prompt","proc:Add Core Rules at Top","proc:Add Memory/Context","proc:Repeat Core Rules at Bottom","end:Send to LLM"]}
    ],
    game:{icon:"📜",title:"Prompt Engineer",desc:"Craft the perfect agent prompt",badges:["✍️ Scribe","📜 Prompt Master","🧠 Whisperer"],challenges:[{icon:"📝",title:"Draft Persona",desc:"Write a persona for a grumpy DBA agent",xp:50},{icon:"🔄",title:"Positive Pivot",desc:"Rewrite a negative constraint positively",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 12+ on MCQs",xp:100}]},
    project:{title:"Dynamic Prompt Builder",badge:"Prompt Smith",desc:"Build a class that constructs a prompt dynamically.",tags:["Python","Prompting"],steps:[{title:"Base Template",desc:"Create a string with placeholders {date}, {os}"},{title:"Rule Builder",desc:"Function to append rules to the end"},{title:"Injection",desc:"Format the string with dynamic data"}],code:`import datetime\n\nclass PromptBuilder:\n    def __init__(self):\n        self.base = "You are a DevOps Agent.\\nDate: {date}\\nOS: {os}\\n"\n        self.rules = []\n    \n    def add_rule(self, rule):\n        self.rules.append(rule)\n        \n    def build(self): \n        context = self.base.format(\n            date=datetime.date.today(), \n            os="MacOS"\n        )\n        rules_str = "\\nCRITICAL RULES:\\n" + "\\n".join(self.rules)\n        return context + rules_str\n\np = PromptBuilder()\np.add_rule("Always verify before deleting.")\nprint(p.build())`}
  },
  t7: {
    tag:'Core Concept · AI Fundamentals', num:7, title:'Tools & Tool Calling', desc:'How LLMs are trained to output structured JSON to execute local functions.',
    theory:`<div class="card"><h3>🔧 Native Tool Calling</h3><p>Historically, developers used prompt engineering (like ReAct) to force LLMs to output JSON. Now, models like GPT-4 and Claude 3 are fine-tuned for <strong>Native Tool Calling (Function Calling)</strong>.</p><h4>How it works:</h4><ol><li>You pass a JSON Schema describing your functions to the API.</li><li>The LLM recognizes if a function helps achieve the goal.</li><li>The API returns a <code>tool_calls</code> object instead of standard text.</li><li>Your code parses this object, runs the function, and returns the result.</li></ol><div class="box b-em"><h5>Best Practices for Tool Schemas</h5><ul><li><strong>Descriptions are critical:</strong> The LLM reads the description to decide <em>when</em> to use the tool. Make it extremely clear.</li><li><strong>Enums:</strong> If an argument has specific allowed values, use JSON Schema enums to prevent hallucinations.</li><li><strong>Few arguments:</strong> Tools with 10 arguments confuse the LLM. Break them into smaller, focused tools.</li></ul></div></div>`,
    mcqs:[
      {q:"What is 'Native Tool Calling' (Function Calling)?",opts:["A. Writing a python function","B. The LLM being fine-tuned to reliably output JSON matching a provided schema","C. Calling a phone number","D. Writing bash scripts"],ans:1,exp:"Native tool calling is a feature built into modern LLM APIs to handle tool selection reliably."},
      {q:"How does the LLM know what tools are available?",opts:["A. It searches the internet","B. You provide an array of JSON Schemas in the API request","C. It guesses based on the prompt","D. It reads your hard drive"],ans:1,exp:"You must explicitly pass the tool definitions in the API request (e.g., the 'tools' parameter in OpenAI)."},
      {q:"What is the most important part of a tool schema for the LLM?",opts:["A. The function name","B. The 'description' field","C. The JSON formatting","D. The language it's written in"],ans:1,exp:"The LLM relies heavily on the 'description' field to understand *when* and *why* to use the tool."},
      {q:"If a tool requires a 'status' argument that must be either 'open' or 'closed', how do you enforce this?",opts:["A. Write it in the prompt","B. Use the 'enum' property in the JSON schema","C. Check it in python after execution","D. Hope the LLM gets it right"],ans:1,exp:"Using 'enum' in the schema strongly guides the LLM to only pick valid options."},
      {q:"What does the LLM return when it decides to call a tool?",opts:["A. The result of the tool","B. A 'tool_calls' array containing the tool name and generated JSON arguments","C. Plain text describing the tool","D. A python script"],ans:1,exp:"The API stops generating text and instead returns a structured tool_calls object."},
      {q:"After the LLM returns a tool call, whose job is it to execute the tool?",opts:["A. OpenAI's servers","B. The user","C. Your local application code","D. The LLM"],ans:2,exp:"The LLM only generates the intent (the JSON args). Your code must actually run the function."},
      {q:"Once your code executes the tool, what do you do next?",opts:["A. Exit the program","B. Send the result back to the LLM in a new message with role 'tool'","C. Print it to the screen and stop","D. Delete the memory"],ans:1,exp:"The result must be passed back to the LLM so it can observe the outcome and continue reasoning."},
      {q:"What happens if a tool requires 15 different arguments?",opts:["A. The LLM handles it perfectly","B. The LLM is likely to hallucinate or miss arguments, reducing reliability","C. It runs faster","D. The API rejects it"],ans:1,exp:"Complex tools degrade LLM performance. It's better to break them into smaller, focused tools."},
      {q:"If an agent needs to get the current time, how should it do it?",opts:["A. By guessing","B. By using a 'get_current_time' tool provided in the schema","C. By reading the system prompt","D. LLMs inherently know the exact time"],ans:1,exp:"LLMs don't have an internal clock. They need a tool to fetch the current time."},
      {q:"What is 'Parallel Tool Calling'?",opts:["A. Running two LLMs at once","B. The LLM deciding to call multiple tools at the exact same time (e.g., get weather for NY and LA)","C. Writing multi-threaded python","D. Calling OpenAI and Anthropic together"],ans:1,exp:"Modern APIs allow the LLM to output an array of multiple tool calls to be executed simultaneously."},
      {q:"Why is parallel tool calling useful?",opts:["A. It saves tokens","B. It reduces latency by doing multiple independent tasks at once before returning to the LLM","C. It prevents hallucinations","D. It uses less RAM"],ans:1,exp:"Executing 3 independent API calls in parallel is much faster than doing them sequentially."},
      {q:"What role does the message containing the tool result have in the OpenAI API?",opts:["A. role: 'user'","B. role: 'system'","C. role: 'tool' (or 'function')","D. role: 'assistant'"],ans:2,exp:"Tool results are appended to the context with a specific role ('tool' or 'function')."},
      {q:"If a tool result is a massive 50MB JSON file, what should your execution layer do?",opts:["A. Send it directly to the LLM","B. Parse, filter, or summarize it to extract only what the LLM needs before sending it back","C. Compress it into a zip file and send it","D. Ignore it"],ans:1,exp:"Sending 50MB of text will exceed the context window and cost a fortune."},
      {q:"How do you force an LLM to ALWAYS use a specific tool?",opts:["A. Ask nicely in the prompt","B. Use the 'tool_choice' parameter in the API (e.g., tool_choice: {name: 'my_tool'})","C. Delete all other tools","D. It's impossible"],ans:1,exp:"The tool_choice parameter allows you to force the model to call a specific tool."},
      {q:"What is the risk of poorly named tools (e.g., tool_1, tool_2)?",opts:["A. Syntax errors","B. The LLM will have no semantic understanding of what they do and will guess randomly","C. They run slower","D. OpenAI bans your account"],ans:1,exp:"Tool names and descriptions are semantic clues. They must be descriptive (e.g., 'search_database')."}
    ],
    flows:[
      {title:"Tool Call Loop",items:["start:Send Context + Tools","proc:LLM Returns tool_calls","proc:App Runs Functions","proc:App Appends tool results","end:Send Back to LLM"]},
      {title:"Schema Design",items:["start:Identify Function","proc:Define Name (Descriptive)","proc:Write clear description","proc:Define Properties (JSON Schema)","end:Add to API Request"]},
      {title:"Parallel Execution",items:["start:LLM returns 3 calls","proc:Async Execute Tool 1","proc:Async Execute Tool 2","proc:Async Execute Tool 3","end:Wait for all, return results"]}
    ],
    game:{icon:"🔧",title:"Tool Architect",desc:"Design and execute robust tools",badges:["📝 Schema Writer","⚡ Async Executor","🔧 Tool Master"],challenges:[{icon:"📝",title:"Schema Design",desc:"Write a schema for 'book_flight'",xp:50},{icon:"⚡",title:"Parallel Logic",desc:"Write python async code to run 2 tools",xp:50},{icon:"🎓",title:"MCQ Master",desc:"Score 12+ on MCQs",xp:100}]},
    project:{title:"Weather Tool Call",badge:"API Caller",desc:"Implement a simple tool call loop with the OpenAI API.",tags:["Python","OpenAI","Tool Calling"],steps:[{title:"Define Tool Schema",desc:"Create get_weather schema"},{title:"Call LLM",desc:"Send prompt: 'What is weather in Paris?'"},{title:"Parse Response",desc:"Check if message.tool_calls exists"},{title:"Execute & Return",desc:"Mock the weather data and send it back"}],code:`import openai\nclient = openai.OpenAI()\n\ntools = [{\n    "type": "function",\n    "function": {\n        "name": "get_weather",\n        "description": "Get current weather in a city",\n        "parameters": {\n            "type": "object",\n            "properties": {"city": {"type": "string"}},\n            "required": ["city"]\n        }\n    }\n}]\n\nmsgs = [{"role":"user", "content":"Weather in Paris?"}]\nresp = client.chat.completions.create(model="gpt-4o", messages=msgs, tools=tools)\ncall = resp.choices[0].message.tool_calls[0]\n\n# Mock execution\nresult = "22C and Sunny"\nmsgs.append(resp.choices[0].message)\nmsgs.append({"role":"tool", "tool_call_id":call.id, "content":result})\n\nfinal = client.chat.completions.create(model="gpt-4o", messages=msgs)\nprint(final.choices[0].message.content)`}
  },
"""

insert_idx = content.find("t21: {")
new_content = content[:insert_idx] + t5_to_t7 + content[insert_idx:]

with open(html_path, "w") as f:
    f.write(new_content)
print("Done inserting t5-t7")
