import re

html_path = "/Users/bhoomim/devops CI:CD/handbook/fullstack_ai_handbook.html"
with open(html_path, "r") as f:
    content = f.read()

rich_content = r"""
  t141: {
    tag:'Phase 5 · System Design', num:141,
    title:'Monolith vs Microservices',
    desc:'The architectural debate on how to structure a massive application.',
    theory:`<div class="card"><h3>🏢 One Building vs A Village</h3><p>A <strong>Monolithic Architecture</strong> means all your code (UI, Billing, Inventory, Users) is compiled into a single massive application and deployed to one server. It is easy to develop and test, but scaling is hard (you have to copy the entire monolith even if only the Billing part is under load).</p><h4>Microservices</h4><p>A <strong>Microservices Architecture</strong> breaks the app into dozens of tiny, independent applications. The <code>BillingService</code> is its own app with its own database. The <code>InventoryService</code> is a separate app. They communicate via HTTP or messaging queues. This allows massive teams to work independently and scale services individually.</p></div>`,
    mcqs:[
      {q:"What is a major advantage of a Monolithic architecture?",opts:["A. It scales infinitely","B. It is incredibly simple to develop, test, debug, and deploy when a project is small or medium-sized","C. It never crashes","D. It uses micro-databases"],ans:1,exp:"Most successful startups begin as a monolith. Microservices add massive complexity."},
      {q:"In a Microservices architecture, how do the independent services usually communicate with each other?",opts:["A. By reading the exact same database","B. Via network calls (HTTP REST APIs, gRPC) or asynchronous Message Brokers (like Kafka)","C. Through global variables","D. Through the browser"],ans:1,exp:"Services should NOT share a single database, as that creates a massive bottleneck (a 'Distributed Monolith')."},
      {q:"What is the concept of 'Polyglot Persistence' in Microservices?",opts:["A. Speaking multiple languages","B. Allowing each individual microservice to use the specific database technology that fits its needs best (e.g., Postgres for Billing, Neo4j for Social Graph, MongoDB for Product Catalog)","C. Keeping all data in RAM","D. Deleting data regularly"],ans:1,exp:"This flexibility is a huge advantage over a monolith's single DB requirement."},
      {q:"What is the biggest downside of moving to Microservices too early?",opts:["A. It's too fast","B. The massive operational complexity. You now have to manage distributed transactions, network latency, network failures, and complex CI/CD pipelines for 50 different apps instead of 1.","C. You run out of IP addresses","D. It costs too much storage"],ans:1,exp:"'Don't even consider microservices unless you have a monolith that is bursting at the seams.' - Martin Fowler"},
      {q:"If the 'Inventory Service' crashes in a well-designed Microservices architecture, what happens to the 'Billing Service'?",opts:["A. It crashes immediately","B. It continues to function independently. This 'Fault Isolation' ensures a bug in one service doesn't take down the entire company.","C. It reboots","D. It takes over inventory"],ans:1,exp:"A monolith goes down completely if a single memory leak occurs anywhere in the codebase."}
    ],
    flows:[
      {title:"Scaling Difference",items:["start:Traffic spike on 'Checkout' Feature","dec:Monolith:","proc:Must copy entire 5GB App x 10 servers","dec:Microservices:","end:Scale ONLY the 'Checkout Service' x 10 containers!"]}
    ],
    game:{icon:"🏢",title:"The Architect",desc:"Master system architectures",badges:["🏢 Monolith Lover","🌐 Microservice Mapper","🛑 Fault Isolator"],challenges:[{icon:"📝",title:"The Shared DB",desc:"Why shouldn't microservices share a DB?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Architecture Choice",badge:"Decider",desc:"Pick the right architecture.",tags:["Design","Concepts"],steps:[{title:"Scenario 1",desc:"A 3-person startup launching an MVP -> Monolith"},{"title:"Scenario 2",desc:"Netflix scaling to 200M users -> Microservices"},{"title:"Rule of Thumb",desc:"Always start with a Monolith."}],code:`// The Microservices Premium:\n// You trade codebase complexity for operational complexity.\n// Writing code becomes easier.\n// Deploying and debugging code becomes a nightmare.`}
  },
  t142: {
    tag:'Phase 5 · System Design', num:142,
    title:'API Gateways',
    desc:'The front door to your microservices architecture.',
    theory:`<div class="card"><h3>🚪 The Front Door</h3><p>If you have 50 microservices, does the Mobile App have to remember 50 different IP addresses and make 50 separate authentication requests? No.</p><h4>The Gateway Pattern</h4><p>You place an <strong>API Gateway</strong> (like AWS API Gateway, Kong, or NGINX) between the internet and your microservices. The Mobile App only talks to ONE endpoint: <code>api.myapp.com</code>. The Gateway handles Authentication, Rate Limiting, and SSL Termination, and then silently routes the request to the correct internal microservice.</p></div>`,
    mcqs:[
      {q:"What specific problem does an API Gateway solve in a Microservices architecture?",opts:["A. It writes the code","B. It prevents the client (like a mobile app) from needing to know the IP addresses and URLs of 50 different backend services. It provides a single unified entry point.","C. It hosts the database","D. It generates CSS"],ans:1,exp:"It acts as a Reverse Proxy."},
      {q:"Where should 'Cross-Cutting Concerns' like SSL Termination (Decrypting HTTPS) and JWT Authentication be handled?",opts:["A. Inside every single microservice","B. At the API Gateway layer. This centralizes security and prevents you from having to write authentication logic 50 times in 50 different services.","C. In the database","D. On the frontend"],ans:1,exp:"The Gateway validates the token, and passes the raw User ID to the internal services."},
      {q:"What is 'Rate Limiting' at the API Gateway?",opts:["A. Speeding up the network","B. Restricting a user or IP address to a certain number of requests per minute (e.g., 100 req/min) to prevent DDoS attacks or server overload","C. Limiting the size of the database","D. Reducing image quality"],ans:1,exp:"If a user exceeds the limit, the Gateway returns a 429 Too Many Requests status."},
      {q:"Can an API Gateway perform 'Request Aggregation'?",opts:["A. No","B. Yes. Instead of the mobile app making 3 separate calls to User Service, Order Service, and Review Service, it makes 1 call to the Gateway. The Gateway makes the 3 internal calls, merges the JSON, and sends 1 response back.","C. Only in Java","D. Only on weekends"],ans:1,exp:"This drastically reduces latency for mobile devices on slow 4G connections."},
      {q:"What is a major risk of using an API Gateway?",opts:["A. It is too secure","B. It becomes a Single Point of Failure (SPOF). If the Gateway goes down, the entire application goes offline, even if the backend services are perfectly healthy.","C. It deletes data","D. It causes memory leaks"],ans:1,exp:"Because of this, Gateways must be highly available, redundant, and horizontally scaled."}
    ],
    flows:[
      {title:"API Gateway Flow",items:["start:Client requests /api/users/profile","proc:Gateway validates JWT Token","dec:Token is Valid!","proc:Gateway routes traffic to User-Service Pod","end:Gateway returns JSON to Client"]}
    ],
    game:{icon:"🚪",title:"The Gatekeeper",desc:"Master API Gateways",badges:["🚪 Bouncer","🛑 Rate Limiter","🛡️ SSL Terminator"],challenges:[{icon:"📝",title:"SPOF",desc:"Why is the Gateway dangerous?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Gateway Design",badge:"Traffic Cop",desc:"Design gateway routing rules.",tags:["Design","API"],steps:[{title:"Route 1",desc:"/api/auth/* -> Auth Service"},{"title:"Route 2",desc:"/api/billing/* -> Billing Service"},{"title:"Auth",desc:"Gateway checks JWT before routing!"}],code:`# Concept of NGINX as an API Gateway\nserver {\n  listen 443 ssl;\n  server_name api.myapp.com;\n\n  location /users/ {\n    # Route to the User microservice\n    proxy_pass http://user-service:3000/;\n  }\n\n  location /billing/ {\n    # Route to the Billing microservice\n    proxy_pass http://billing-service:4000/;\n  }\n}`}
  },
  t143: {
    tag:'Phase 5 · System Design', num:143,
    title:'Message Brokers (Kafka)',
    desc:'Asynchronous communication to decouple services and handle massive traffic spikes.',
    theory:`<div class="card"><h3>📨 The Post Office</h3><p>If the Order Service makes a synchronous HTTP request to the Email Service, and the Email Service is down, the HTTP request fails, and the user gets an error. This is tight coupling.</p><h4>Event-Driven Architecture</h4><p>Instead, the Order Service publishes a message (<code>OrderPlacedEvent</code>) to a <strong>Message Broker</strong> like Apache Kafka or RabbitMQ. It immediately returns "Success" to the user. The Email Service checks the Broker whenever it is ready, and processes the email asynchronously.</p><div class="box b-am"><h5>Handling Spikes</h5><p>If 100,000 orders happen in 1 minute, the Email service won't crash. The Broker acts as a massive shock-absorber (buffer), holding the 100,000 messages securely while the Email service processes them at its own pace.</p></div></div>`,
    mcqs:[
      {q:"What is the primary benefit of using a Message Broker (like Kafka or RabbitMQ) for service-to-service communication instead of HTTP REST?",opts:["A. It is faster than HTTP","B. It provides Asynchronous Decoupling. If the receiving service is offline, the sender doesn't crash; the message is safely stored in the queue until the receiver comes back online.","C. It encrypts the data","D. It compresses the data"],ans:1,exp:"HTTP is synchronous (I wait for your reply). Messaging is asynchronous (I drop off the letter and walk away)."},
      {q:"What does it mean when a Message Broker acts as a 'Buffer' or 'Shock Absorber'?",opts:["A. It stops physical shocks","B. During massive traffic spikes, the broker queues up the millions of requests, allowing the backend services to process them at a safe, steady pace without being overwhelmed and crashing.","C. It deletes extra messages","D. It slows down the internet"],ans:1,exp:"This is how Ticketmaster handles the moment Taylor Swift tickets go on sale."},
      {q:"In the Pub/Sub (Publish/Subscribe) pattern, how do services communicate?",opts:["A. They call each other directly","B. A 'Publisher' service sends a message to a 'Topic'. Multiple 'Subscriber' services can listen to that Topic and react independently. The Publisher doesn't know or care who is listening.","C. They use a database","D. They send emails"],ans:1,exp:"When a user registers, the Auth service publishes 'UserCreated'. The Email service sends a welcome email. The Analytics service updates a dashboard. Neither knows about the other!"},
      {q:"What is a major architectural difference between Apache Kafka and RabbitMQ?",opts:["A. RabbitMQ is a traditional queue (messages are deleted after being read). Kafka is a distributed event streaming log (messages are stored permanently on disk, allowing consumers to 'rewind' and replay past events).","B. Kafka is a database, RabbitMQ is a cache","C. RabbitMQ is only for Java","D. There is no difference"],ans:0,exp:"Kafka is essentially a highly scalable, append-only text file."},
      {q:"What is a downside of introducing a Message Broker?",opts:["A. It makes the system too fast","B. Eventual Consistency. Because communication is asynchronous, the database might take a few seconds to update, meaning the user might not see their change immediately on the UI.","C. It costs too much RAM","D. It breaks HTTP"],ans:1,exp:"'Your order is processing...' is the UI solution to Eventual Consistency."}
    ],
    flows:[
      {title:"Asynchronous Queue Flow",items:["start:User clicks 'Checkout' (100k times)","proc:OrderService puts 100k messages in Kafka Queue","dec:OrderService instantly tells User 'Success!'","proc:EmailService slowly reads 5 msgs/sec from Queue","end:System stays alive under massive load!"]}
    ],
    game:{icon:"📨",title:"The Postman",desc:"Master async messaging",badges:["📨 Publisher","🎧 Subscriber","🧽 Shock Absorber"],challenges:[{icon:"📝",title:"Decoupling",desc:"Why is sync HTTP dangerous?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Pub/Sub Concept",badge:"Broadcaster",desc:"Design a Pub/Sub event.",tags:["Design","Kafka"],steps:[{title:"Event",desc:"UserAccountCreated"},{"title:"Publisher",desc:"Auth Service broadcasts the event to Kafka"},{"title:"Subscribers",desc:"Email Service (Welcome), DB Service (Setup)"}],code:`// Mental Model of Asynchronous Messaging\n\n// 1. Synchronous (Bad for critical paths):\nawait EmailService.send(user); // If EmailService is down, the whole app crashes!\n\n// 2. Asynchronous (Good):\nKafka.publish('USER_REGISTERED', user);\n// App continues instantly. EmailService will read it whenever it wakes up!`}
  },
  t144: {
    tag:'Phase 5 · System Design', num:144,
    title:'Caching Strategies (Redis)',
    desc:'Drastically improving performance and saving database load using in-memory caches.',
    theory:`<div class="card"><h3>⚡ The Fast Lane</h3><p>Querying a SQL database on a hard drive is slow. If 1 million users view the homepage, running the same complex SQL join 1 million times will crash the database.</p><h4>Redis (Remote Dictionary Server)</h4><p>A cache (like Redis or Memcached) stores data entirely in <strong>RAM</strong>. Reading from RAM is infinitely faster than reading from a hard drive. When a user requests the homepage, you check the Cache. If it's there (Cache Hit), you return it instantly. If not (Cache Miss), you query the DB, save the result to the Cache, and then return it.</p></div>`,
    mcqs:[
      {q:"Why is a Cache (like Redis) orders of magnitude faster than a standard Database (like Postgres)?",opts:["A. It uses better algorithms","B. It stores data purely in RAM (System Memory), avoiding the incredibly slow process of reading from physical Disk (Hard Drives).","C. It ignores security","D. It is written in C++"],ans:1,exp:"The tradeoff is that RAM is expensive, so caches are small compared to databases."},
      {q:"What is a 'Cache Miss'?",opts:["A. When the cache deletes data","B. When the application looks for data in the cache, but it is not there. The app must then fall back to querying the slow, primary database.","C. When the cache crashes","D. When the data is wrong"],ans:1,exp:"A high Cache Hit ratio is the goal of caching."},
      {q:"What is Cache Invalidation, and why is it notoriously difficult?",opts:["A. It means deleting the cache","B. It is the process of updating or deleting cached data when the source database changes. If you fail to invalidate it, the user will see stale/old data on the website.","C. It means the cache is broken","D. It means the cache is full"],ans:1,exp:"'There are only two hard things in Computer Science: cache invalidation and naming things.' - Phil Karlton"},
      {q:"What is the 'Cache-Aside' strategy?",opts:["A. Putting the cache physically next to the server","B. The application checks the cache first. If Miss, it queries the DB, writes the data into the cache for next time, and returns it.","C. The database updates the cache","D. The cache updates the database"],ans:1,exp:"This is the most common caching pattern in web development."},
      {q:"What does 'TTL' stand for in caching?",opts:["A. Time to Live. An expiration timer placed on a cached item (e.g., 60 seconds). When time runs out, the item is automatically deleted, forcing a fresh database query next time.","B. Total Technical Limit","C. Time to Load","D. Text to Link"],ans:0,exp:"TTL is the easiest way to solve the Cache Invalidation problem."}
    ],
    flows:[
      {title:"Cache-Aside Flow",items:["start:User requests Top 10 Products","dec:Check Redis Cache (Cache Hit?)","proc:(No) Query Postgres DB (Slow: 500ms)","dec:Save result to Redis with TTL=1 hr","end:(Yes) Return from Redis (Fast: 5ms)"]}
    ],
    game:{icon:"⚡",title:"The Speeder",desc:"Master Caching",badges:["⚡ RAM Reader","🎯 Cache Hitter","🕰️ TTL Setter"],challenges:[{icon:"📝",title:"Stale Data",desc:"What happens if you don't invalidate?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Redis Node Script",badge:"Cacher",desc:"Implement a Cache-Aside function.",tags:["Node.js","Redis"],steps:[{title:"Check",desc:"const cached = await redis.get('data')"},{"title:"Miss",desc:"if(!cached) { const db = await query() }"},{"title:"Set",desc:"redis.setex('data', 3600, db) // 1 hr TTL"}],code:`// Standard Cache-Aside Pattern in Node.js\nasync function getHomepageData() {\n  // 1. Check Cache\n  const cached = await redis.get('homepage_feed');\n  if (cached) return JSON.parse(cached);\n\n  // 2. Cache Miss! Query the slow database\n  const freshData = await database.query('SELECT complex_stuff...');\n\n  // 3. Save to Cache for the next user (Expires in 60 seconds)\n  await redis.setex('homepage_feed', 60, JSON.stringify(freshData));\n\n  return freshData;\n}`}
  },
  t145: {
    tag:'Phase 5 · System Design', num:145,
    title:'Database Scaling',
    desc:'Replication and Sharding: How to handle terabytes of data and millions of reads.',
    theory:`<div class="card"><h3>🗄️ Splitting the Load</h3><p>If your Postgres database server reaches 100% CPU, you can scale <strong>Vertically</strong> (buy a more expensive server with more RAM). But eventually, you hit a hardware limit. You must scale <strong>Horizontally</strong> (add more servers).</p><h4>Read Replicas (Replication)</h4><p>You have 1 Master database (for Writes/Updates). You create 3 Slave databases (Read Replicas). The Master copies its data to the slaves. Now, your API routes all SELECT queries to the 3 slaves, instantly quadrupling your read capacity!</p><h4>Sharding (Partitioning)</h4><p>What if your database is 50 Terabytes and doesn't fit on one hard drive? You use <strong>Sharding</strong>. You put Users A-M on Database 1, and Users N-Z on Database 2.</p></div>`,
    mcqs:[
      {q:"What is the difference between Vertical Scaling and Horizontal Scaling?",opts:["A. Vertical means buying a bigger, faster server (more RAM/CPU). Horizontal means adding more, cheaper servers to a cluster.","B. Vertical is for SQL, Horizontal is for NoSQL","C. Vertical is free, Horizontal costs money","D. Vertical is software, Horizontal is hardware"],ans:0,exp:"Vertical scaling has a hard physical limit. Horizontal scaling is infinite."},
      {q:"In a Master-Slave Database Replication setup, how is traffic usually routed?",opts:["A. Randomly","B. ALL Writes (Inserts, Updates, Deletes) go to the Master. ALL Reads (SELECTs) go to the Slaves (Read Replicas).","C. Writes to Slaves, Reads to Master","D. Everything goes to the Master"],ans:1,exp:"Most web applications are extremely 'Read-Heavy' (e.g., viewing tweets vs writing a tweet), making Replicas incredibly effective."},
      {q:"What is a major challenge with Master-Slave replication?",opts:["A. It deletes data","B. Replication Lag. It takes a few milliseconds for the Master to copy the new data to the Slaves. A user might update their profile and instantly refresh the page, but see the old data because they read from a Slave that hasn't synced yet.","C. It makes reads slower","D. It requires manual copying"],ans:1,exp:"This is another form of 'Eventual Consistency'."},
      {q:"What is Database Sharding?",opts:["A. Deleting old data","B. Splitting a single massive table across multiple completely separate database servers (e.g., Server A holds users from USA, Server B holds users from Europe)","C. Encrypting the database","D. Combining two databases"],ans:1,exp:"Sharding is incredibly complex to manage. Avoid it until absolutely necessary."},
      {q:"Why do NoSQL databases (like Cassandra or MongoDB) excel at Horizontal Scaling compared to traditional SQL databases?",opts:["A. Because they don't have schemas","B. Because NoSQL drops strict ACID compliance and Complex Joins, which are the two things that make horizontally distributing relational data mathematically difficult","C. Because NoSQL is written in Java","D. Because they run on Windows"],ans:1,exp:"If you need massive horizontal write-scale, you usually have to abandon Relational Joins."}
    ],
    flows:[
      {title:"Master-Slave Flow",items:["start:User creates Post (POST Request)","proc:API writes to MASTER Database","dec:MASTER asynchronously syncs data to 3 SLAVES","proc:User views timeline (GET Request)","end:API reads from SLAVE Database (Load Balanced!)"]}
    ],
    game:{icon:"🗄️",title:"The Scaler",desc:"Master database scaling",badges:["🗄️ Horizontal Scaler","📖 Read Replica Maker","🪓 Sharder"],challenges:[{icon:"📝",title:"Replication Lag",desc:"Explain why a user might see old data.",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Scaling Concepts",badge:"Architect",desc:"Determine the scaling method.",tags:["Design","Database"],steps:[{title:"Problem 1",desc:"DB is at 100% CPU from SELECT queries -> Add Read Replicas"},{"title:"Problem 2",desc:"DB is out of Hard Drive space -> Implement Sharding"},{"title:"Problem 3",desc:"DB needs slightly more RAM -> Vertical Scaling (Upgrade Instance)"}],code:`// Database Scaling Rule of Thumb:\n// 1. Optimize your SQL Queries and add Indexes.\n// 2. Add a Redis Cache.\n// 3. Upgrade to a bigger server (Vertical).\n// 4. Add Read Replicas.\n// 5. Shard the database (Only if you are Netflix).`}
  },
  t146: {
    tag:'Phase 5 · AI Engineering', num:146,
    title:'Large Language Models (LLMs)',
    desc:'The foundation of modern AI: How they work and how to prompt them effectively.',
    theory:`<div class="card"><h3>🧠 The Next Token Predictor</h3><p>An LLM (like GPT-4 or Gemini) is not a database of facts. It is a massive statistical engine (a Neural Network) trained on terabytes of text. Its only function is to look at a sequence of words and predict the most mathematically probable <strong>next word (token)</strong>.</p><h4>Prompt Engineering</h4><p>Because they are predictive engines, the context you provide is everything. Good Prompt Engineering involves giving the model a <strong>Persona</strong>, highly specific <strong>Context/Rules</strong>, and a requested <strong>Format</strong> (like JSON).</p></div>`,
    mcqs:[
      {q:"At a fundamental level, what is an LLM (Large Language Model) actually doing when it generates text?",opts:["A. Searching Google for the answer","B. Looking at the context provided and statistically predicting the most likely NEXT word (token), one word at a time","C. Querying a database of facts","D. Running a logic simulator"],ans:1,exp:"It is essentially the world's most advanced autocorrect."},
      {q:"What is 'Hallucination' in the context of LLMs?",opts:["A. When the AI crashes","B. When the model confidently generates false, fabricated, or nonsensical information because it was mathematically probable based on the prompt's context, even though it isn't factual","C. When the AI sees images","D. When the AI refuses to answer"],ans:1,exp:"Because they are not databases, they don't 'know' what is true. They only know what sounds correct."},
      {q:"What is the 'Context Window' of an LLM?",opts:["A. The screen it runs on","B. The maximum number of tokens (words/characters) the model can process and remember at one single time during a conversation","C. The database size","D. The training data"],ans:1,exp:"If a model has a 4000 token context window, it physically cannot read a 10,000 word book in one prompt."},
      {q:"Which of the following makes a high-quality Prompt?",opts:["A. 'Write code for a website'","B. 'Act as a Senior React Engineer. Write a React component for a login form using Tailwind CSS. Return ONLY the code.'","C. 'Do my homework'","D. 'Make a good app'"],ans:1,exp:"Persona + Context + Specific Constraints = Great Prompt."},
      {q:"What does the 'Temperature' parameter do in an LLM API request?",opts:["A. Checks the weather","B. Controls the randomness/creativity of the output. Temperature 0 makes it deterministic and focused. Temperature 1 makes it creative and unpredictable.","C. Controls the speed of generation","D. Controls the length of the output"],ans:1,exp:"Use Temp 0 for code generation and factual data extraction."}
    ],
    flows:[
      {title:"LLM Next Token Flow",items:["start:Prompt: 'The sky is so...'","proc:Model calculates probabilities","dec:'blue' (95%), 'beautiful' (4%), 'cheese' (0.01%)","proc:Outputs 'blue'","end:New Context: 'The sky is so blue'. Predicts next..."]}
    ],
    game:{icon:"🧠",title:"The Prompter",desc:"Master LLM interactions",badges:["🧠 Context Provider","🌡️ Temperature Controller","🛑 Hallucination Spotter"],challenges:[{icon:"📝",title:"The Core",desc:"What is an LLM fundamentally?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"API System Prompt",badge:"Engineer",desc:"Write a system prompt for an API.",tags:["AI","Prompting"],steps:[{title:"Persona",desc:"You are a helpful JSON data extractor."},{"title:"Rules",desc:"Extract names. Do not include markdown."},{"title:"Format",desc:"Output ONLY valid JSON."}],code:`// Node.js API call to an LLM\nconst response = await openai.chat.completions.create({\n  model: "gpt-4",\n  temperature: 0.0, // Strict, deterministic output\n  messages: [\n    {\n      role: "system",\n      content: "You are a data extractor. Return ONLY valid JSON. No explanations."\n    },\n    {\n      role: "user",\n      content: "Extract the name and age from: 'Bhoomi is 25 years old'."\n    }\n  ]\n});`}
  },
  t147: {
    tag:'Phase 5 · AI Engineering', num:147,
    title:'Embeddings & Vector Databases',
    desc:'Giving AI long-term memory and the ability to understand semantic meaning.',
    theory:`<div class="card"><h3>🔢 Turning Meaning into Math</h3><p>An LLM only understands numbers. An <strong>Embedding Model</strong> takes text (like a sentence) and converts it into a massive array of numbers (e.g., 1536 dimensions) called a Vector. This array mathematically represents the <em>semantic meaning</em> of the text.</p><h4>Vector Databases (Pinecone/Milvus)</h4><p>If you embed the word "Dog" and the word "Puppy", their number arrays will be mathematically very close to each other in 3D space. You store these vectors in a <strong>Vector Database</strong>. Now, you can perform a "Similarity Search" to find documents related to a user's query, even if they don't share any exact keywords!</p></div>`,
    mcqs:[
      {q:"What is an Embedding?",opts:["A. Putting a video on a website","B. A mathematical representation (a high-dimensional vector/array of numbers) of the semantic meaning of a piece of text","C. A type of database","D. A neural network layer"],ans:1,exp:"It converts human meaning into a coordinate point in space."},
      {q:"How does an Embedding Model help search engines compare concepts?",opts:["A. By matching exact letters","B. It places concepts with similar meanings close together in mathematical space. 'King' and 'Queen' will be closer together than 'King' and 'Car'.","C. By querying Wikipedia","D. By using alphabetical order"],ans:1,exp:"This is the foundation of Semantic Search."},
      {q:"What is a Vector Database (like Pinecone, Milvus, or Qdrant)?",opts:["A. A traditional SQL database","B. A database specifically designed to store, manage, and perform ultra-fast similarity searches on massive arrays of numbers (Embeddings)","C. A graph database","D. A cache"],ans:1,exp:"Standard Postgres struggles to compare 1536-dimensional arrays quickly without extensions like pgvector."},
      {q:"In a Vector Database, how do you find the most relevant documents for a user's search query?",opts:["A. Using 'SELECT * WHERE text LIKE %query%'","B. By embedding the user's search query into a vector, and then calculating the distance (e.g., Cosine Similarity) between that query vector and all the document vectors in the DB to find the nearest neighbors","C. By using alphabetical sorting","D. By asking an LLM"],ans:1,exp:"Cosine Similarity is the math that determines how 'close' two concepts are."},
      {q:"Why do we use Semantic Search (Embeddings) instead of traditional Keyword Search (Elasticsearch)?",opts:["A. It is older","B. Keyword search fails if the exact word isn't used. Semantic search understands intent. A search for 'feline' will successfully match a document about 'cats'.","C. It uses less memory","D. It is easier to set up"],ans:1,exp:"Modern AI apps use Hybrid Search (combining Keyword and Semantic) for the best results."}
    ],
    flows:[
      {title:"Semantic Search Flow",items:["start:User searches: 'How to make a web page?'","proc:Embedding API converts query to Vector [0.1, 0.5...]","dec:Vector DB performs Cosine Similarity Search","proc:DB finds closest Vector (Text: 'HTML Tutorial')","end:Returns 'HTML Tutorial' to user!"]}
    ],
    game:{icon:"🔢",title:"The Mathematician",desc:"Master Embeddings",badges:["🔢 Vectorizer","📐 Distance Calculator","🔎 Semantic Searcher"],challenges:[{icon:"📝",title:"Cosine Similarity",desc:"What does it calculate?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Vector Concept",badge:"Spatial Thinker",desc:"Understand spatial relationships.",tags:["AI","Data"],steps:[{title:"Embed",desc:"Word 'Apple' -> [0.9, 0.1]"},{"title:"Embed",desc:"Word 'Banana' -> [0.8, 0.2] (Very close!)"},{"title:"Embed",desc:"Word 'Car' -> [-0.5, 0.9] (Far away!)"}],code:`// Pseudocode for a Semantic Search Implementation\n\n// 1. Convert user's text into an array of numbers\nconst queryVector = await openai.embeddings.create("How do I center a div?");\n\n// 2. Ask Vector DB for the 3 closest matches in mathematical space\nconst results = await pineconeDB.query({\n  vector: queryVector,\n  topK: 3,\n});\n\n// 3. Results will return documents about CSS Flexbox, \n// even if the user didn't type the word 'CSS'!`}
  },
  t148: {
    tag:'Phase 5 · AI Engineering', num:148,
    title:'RAG (Retrieval-Augmented Generation)',
    desc:'The definitive architecture for building AI apps that know your private data without hallucinating.',
    theory:`<div class="card"><h3>📚 Open Book Exams</h3><p>ChatGPT doesn't know about your company's private HR policies. You cannot fit a 500-page PDF into the prompt context window. Training a custom model is way too expensive.</p><h4>The RAG Architecture</h4><p>RAG solves this by treating the LLM like a student taking an open-book exam.</p><ol><li><strong>Retrieve:</strong> The user asks a question. You embed the question, search your Vector DB, and retrieve the 3 most relevant paragraphs from the PDF.</li><li><strong>Augment:</strong> You combine the retrieved paragraphs with the user's question into a massive prompt.</li><li><strong>Generate:</strong> The LLM reads the paragraphs and generates a factual answer based ONLY on the provided context!</li></ol></div>`,
    mcqs:[
      {q:"What is the primary problem that RAG (Retrieval-Augmented Generation) solves?",opts:["A. It makes the AI generate images","B. It allows an LLM to answer questions based on a massive corpus of private, proprietary data (like internal company documents) without having to spend millions fine-tuning the model","C. It makes the model faster","D. It compresses the data"],ans:1,exp:"RAG completely revolutionized the enterprise AI industry."},
      {q:"How does RAG significantly reduce AI 'Hallucinations'?",opts:["A. By turning the temperature to 1","B. By providing the exact factual documents in the prompt and instructing the model: 'Answer the question based ONLY on the following context. If you don't know, say I don't know.'","C. By deleting the database","D. By using an older model"],ans:1,exp:"You are forcing the model to act as a reading-comprehension engine, not an encyclopedia."},
      {q:"What is the 'Retrieval' phase of RAG?",opts:["A. Retrieving the API key","B. Taking the user's query, converting it to an embedding, and querying a Vector Database to fetch the top 3-5 most semantically relevant text chunks from your documents","C. Retrieving the final answer","D. Fetching data from a standard SQL database"],ans:1,exp:"If the Retrieval phase fails to find the right documents, the Generation phase will fail."},
      {q:"What is 'Chunking' in a RAG pipeline?",opts:["A. Breaking the AI into pieces","B. The pre-processing step where you break a massive 500-page PDF into small, 500-word paragraphs (chunks) BEFORE embedding them and storing them in the Vector DB","C. Deleting old data","D. Grouping users together"],ans:1,exp:"If you embed a whole book as one vector, the search will be incredibly diluted and inaccurate."},
      {q:"What are the two core technologies required to build a RAG application?",opts:["A. React and CSS","B. An Embedding Model (paired with a Vector DB) AND a Text Generation LLM","C. A SQL DB and a NoSQL DB","D. AWS and Azure"],ans:1,exp:"Embeddings find the data. The LLM reads the data and formulates the response."}
    ],
    flows:[
      {title:"The Complete RAG Flow",items:["start:User: 'What is our refund policy?'","proc:App Embeds query -> Vector DB Search","proc:DB returns Chunk #42 ('Refunds are 30 days')","dec:App builds Prompt: Context=[Chunk 42] + Query","end:LLM reads prompt, outputs: 'You have 30 days.'"]}
    ],
    game:{icon:"📚",title:"The Librarian",desc:"Master RAG architectures",badges:["📚 Open Book Taker","🪓 Chunker","🛑 Anti-Hallucinator"],challenges:[{icon:"📝",title:"The Prompt",desc:"What instruction stops hallucinations?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"RAG Prompt Design",badge:"Augmenter",desc:"Write the final augmented prompt.",tags:["AI","RAG"],steps:[{title:"System",desc:"You are a bot. Use only the provided context."},{"title:"Context",desc:"<Inject the 3 paragraphs from the Vector DB here>"},{"title:"Query",desc:"<Inject the user's question here>"}],code:`// The Magic of RAG: The Augmented Prompt\nconst finalPrompt = \`\n  You are a helpful assistant.\n  Answer the user's question based ONLY on the provided context.\n  If the answer is not in the context, reply "I do not know".\n\n  --- CONTEXT ---\n  \${retrievedDocumentsFromVectorDB}\n  ---------------\n\n  USER QUESTION: \${userQuery}\n\`;\n\n// Send finalPrompt to OpenAI...`}
  },
  t149: {
    tag:'Phase 5 · AI Engineering', num:149,
    title:'AI Agents & Tool Calling',
    desc:'Giving LLMs the ability to take actions in the real world.',
    theory:`<div class="card"><h3>🤖 The Autonomous Worker</h3><p>A standard LLM is trapped in a chat box. It can't browse the web, execute code, or send an email. But what if you give it hands?</p><h4>Function Calling (Tool Use)</h4><p>Modern LLMs can be provided with a list of "Tools" (API functions you wrote, like <code>getWeather(location)</code> or <code>sendEmail(to, body)</code>). The LLM reads the user prompt, realizes it needs the weather, and outputs a JSON command telling YOUR backend to run the <code>getWeather</code> function. Your backend runs it, returns the result to the LLM, and the LLM formulates the final answer!</p><h4>Agents</h4><p>An <strong>Agent</strong> is a system where the LLM is given an overarching goal, a set of tools, and a loop (like LangChain or AutoGPT) allowing it to think, execute a tool, observe the result, and decide what to do next entirely autonomously.</p></div>`,
    mcqs:[
      {q:"What does 'Function Calling' or 'Tool Use' mean in the context of LLMs?",opts:["A. The LLM writes code for you","B. The LLM is provided a list of functions it is allowed to use. It can output a JSON instruction asking the developer's server to execute a specific function to gather real-world data or take an action.","C. The LLM fixes computer hardware","D. Calling AWS support"],ans:1,exp:"The LLM itself cannot execute code. It just asks YOUR server to execute the code."},
      {q:"If a user asks an LLM 'What is the weather in Paris today?', how does Tool Calling solve this?",opts:["A. The LLM guesses based on training data","B. The LLM halts generation, asks the server to run the 'getWeather(Paris)' tool, the server returns '70 degrees', and the LLM resumes generation to say 'It is 70 degrees'.","C. It tells the user to check Google","D. It generates an image of the sun"],ans:1,exp:"This bridges the gap between static training data and real-time APIs."},
      {q:"What fundamentally differentiates an 'AI Agent' from a standard RAG chatbot?",opts:["A. Agents have more parameters","B. Agents operate in a loop (Think -> Act -> Observe). They can autonomously decide a sequence of tools to use over multiple steps to achieve a complex goal without human intervention.","C. Chatbots are smarter","D. Agents are written in Python"],ans:1,exp:"An agent could be told: 'Research competitor pricing, write a report, and email it to my boss.'"},
      {q:"What is the 'ReAct' (Reasoning and Acting) framework?",opts:["A. A JavaScript UI library","B. A popular prompt structure for Agents where the model outputs a 'Thought' (what should I do?), an 'Action' (which tool to call), and an 'Observation' (the tool result) in a continuous loop.","C. A database strategy","D. A video game engine"],ans:1,exp:"This structured thinking allows the model to correct itself if a tool fails."},
      {q:"What is a major danger of giving AI Agents access to Tools?",opts:["A. They run out of memory","B. Unintended consequences. If an agent has a 'deleteDatabase' or 'sendEmail' tool, a hallucination could cause it to autonomously destroy data or spam users.","C. They get tired","D. They become self aware"],ans:1,exp:"Always implement 'Human-in-the-Loop' (requiring user approval) for destructive tools."}
    ],
    flows:[
      {title:"The Agent ReAct Loop",items:["start:Goal: 'Find cheap flight to NY and email me'","proc:Thought: I need flight prices -> Action: flightSearchTool()","proc:Observation: API returns $200","dec:Thought: I need to email -> Action: emailTool()","end:Observation: Email sent! Goal Achieved."]}
    ],
    game:{icon:"🤖",title:"The Operator",desc:"Master AI Agents",badges:["🤖 Tool Maker","🔁 ReAct Looper","🛑 Human In The Loop"],challenges:[{icon:"📝",title:"The Executor",desc:"Does the LLM run the tool itself?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Define a Tool",badge:"Blacksmith",desc:"Define a JSON schema for a tool.",tags:["AI","Tools"],steps:[{title:"Name",desc:"name: 'get_stock_price'"},{"title:"Desc",desc:"'Gets real-time price of a ticker'"},{"title:"Params",desc:"type: string, description: 'The stock ticker (e.g. AAPL)'"}],code:`// Telling the LLM what tools it has access to\nconst tools = [\n  {\n    type: "function",\n    function: {\n      name: "get_current_weather",\n      description: "Get the current weather in a given location",\n      parameters: {\n        type: "object",\n        properties: {\n          location: {\n            type: "string",\n            description: "The city and state, e.g. San Francisco, CA",\n          },\n        },\n        required: ["location"],\n      },\n    },\n  }\n];`}
  },
  t150: {
    tag:'Phase 5 · The End', num:150,
    title:'The Future of Software Engineering',
    desc:'Adapting to the AI revolution and the shift from coding to orchestrating.',
    theory:`<div class="card"><h3>🌅 The Final Milestone</h3><p>Congratulations, you have completed the Full-Stack AI Engineer Syllabus! You understand Variables, Data Structures, Spring Boot, React, Kubernetes, and RAG.</p><h4>Where do we go from here?</h4><p>The role of the Software Engineer is changing. AI tools (like Copilot and Devin) will write the boilerplate code, build the HTML, and configure the YAML files. <strong>Your job is no longer to be a syntax memorizer. Your job is to be an Architect.</strong></p><p>You must understand the deep concepts (State, Data Flow, Networking, Decoupling, Security). You will dictate the high-level architecture, orchestrate the AI agents, and validate their outputs. Welcome to the future.</p></div>`,
    mcqs:[
      {q:"How is AI fundamentally changing the role of a Software Engineer?",opts:["A. It will completely replace all human thought","B. It shifts the role from 'Writing raw syntax' to 'Systems Architecture, Orchestration, and Validation'. The engineer focuses on the 'What' and 'Why', while the AI handles the 'How'.","C. It makes engineers type faster","D. It means everyone has to learn C++"],ans:1,exp:"The barrier to entry for coding is dropping. The barrier to entry for scalable architecture is rising."},
      {q:"Why is understanding core fundamentals (like the ones in this syllabus) MORE important in the age of AI?",opts:["A. Because AI doesn't know fundamentals","B. Because if you don't understand how things actually work under the hood (Event loops, DB Indexes, VPCs), you cannot debug or validate the code the AI generates for you. You become a liability.","C. It isn't important anymore","D. Because they are on a test"],ans:1,exp:"An AI can generate a Dockerfile. Only a senior engineer knows WHY the Dockerfile is causing a memory leak in production."},
      {q:"What is 'AI-Assisted Development'?",opts:["A. Buying a robot","B. Pairing human creativity, business context, and architectural vision with the raw generative speed of LLMs to build software 10x faster","C. Using AI to replace the CEO","D. Doing nothing"],ans:1,exp:"You are now a manager, and the LLM is your junior developer."},
      {q:"What is the most valuable skill a developer can cultivate moving forward?",opts:["A. Memorizing CSS selectors","B. Adaptability, deep system-level thinking, and the ability to clearly communicate requirements to both humans and machines (Prompt Engineering)","C. Typing 150 words per minute","D. Learning binary"],ans:1,exp:"Syntax changes. Logical problem-solving does not."},
      {q:"Have you finished the Full-Stack AI Engineer Handbook?",opts:["A. No","B. YES. I am ready to build.","C. Maybe","D. I need to read it again"],ans:1,exp:"Congratulations. You have reached the summit."}
    ],
    flows:[
      {title:"The Future Workflow",items:["start:Human: Defines Business Goal & Architecture","proc:AI: Generates initial Code & Tests","dec:Human: Reviews, Refines, and Connects systems","proc:AI: Deploys via automated CI/CD","end:Human: Monitors observability and iterates!"]}
    ],
    game:{icon:"🌅",title:"The Architect",desc:"Complete the journey",badges:["🏆 Full-Stack Master","🎓 AI Engineer","🚀 Future Ready"],challenges:[{icon:"📝",title:"The End",desc:"What is your new role?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Graduation",badge:"Graduate",desc:"You made it to the end.",tags:["Success","Life"],steps:[{title:"Reflect",desc:"Look at how far you've come (T1 to T150)."},{"title:"Build",desc:"Stop reading. Start building real projects."},{"title:"Innovate",desc:"Use your new skills to change the world."}],code:`// System.exit(0);\n// EOF\n\nconsole.log("Congratulations, Engineer.");`}
  }
"""

start_marker = "};\n\nlet userXP"
inject_idx = content.find(start_marker)

if inject_idx != -1:
    new_content = content[:inject_idx] + ",\n" + rich_content + content[inject_idx:]
    with open(html_path, "w") as f:
        f.write(new_content)
    print("Successfully generated T141-T150 rich content!")
else:
    print("Could not find injection point.")
