import re

html_path = "/Users/bhoomim/devops CI:CD/handbook/fullstack_ai_handbook.html"
with open(html_path, "r") as f:
    content = f.read()

rich_content = r"""
  t91: {
    tag:'Phase 2 · Databases', num:91,
    title:'SQL vs NoSQL',
    desc:'The fundamental choice between strict relational tables and flexible document stores.',
    theory:`<div class="card"><h3>🗄️ The Database Divide</h3><p>When starting a project, you must choose how to store your data. This choice heavily impacts how your application scales and evolves.</p><h4>SQL (Relational)</h4><p>MySQL, PostgreSQL, Oracle. Data is highly structured into <strong>Tables</strong> (Rows and Columns). The schema is strict. If you want to add a 'middle_name' to a User, you must alter the entire table schema. Excellent for complex queries and strict data integrity (ACID).</p><h4>NoSQL (Non-Relational)</h4><p>MongoDB, Cassandra, Redis. Data is flexible. Often stored as <strong>JSON Documents</strong> (or Key-Value pairs). You can store a User with a 'middle_name' right next to a User without one; there is no strict schema. Excellent for rapid prototyping, unstructured data, and massive horizontal scaling.</p></div>`,
    mcqs:[
      {q:"What is a primary characteristic of a SQL (Relational) database?",opts:["A. It stores data in flexible JSON documents","B. It requires a strict, predefined Schema (Tables with specific Columns and Data Types) before you can insert any data","C. It only stores images","D. It cannot handle relationships"],ans:1,exp:"SQL databases enforce strict rules. A string cannot be inserted into an Integer column."},
      {q:"Why might a startup choose a NoSQL database (like MongoDB) for rapid prototyping?",opts:["A. Because it is older and more stable","B. Because it is 'Schemaless'. Developers can freely change the shape of the data (adding/removing fields in the JSON) on the fly without running complex database migrations.","C. Because it is encrypted","D. Because it requires less RAM"],ans:1,exp:"Flexibility is the superpower of Document databases. You can iterate incredibly fast."},
      {q:"If your application handles complex financial transactions (like transferring money between accounts), which database type is preferred?",opts:["A. NoSQL (MongoDB)","B. SQL (PostgreSQL/MySQL)","C. In-Memory (Redis)","D. Text Files"],ans:1,exp:"SQL databases guarantee ACID compliance, ensuring that partial transactions never corrupt financial data."},
      {q:"How do SQL databases typically scale?",opts:["A. They don't scale","B. Vertically (Scaling Up) - Buying a bigger, more expensive server with more RAM and CPU","C. Horizontally (Scaling Out) - Adding hundreds of cheap servers","D. By deleting old data"],ans:1,exp:"While SQL can scale horizontally (sharding), it is notoriously difficult because relational joins across different servers are extremely slow. NoSQL is built to scale horizontally out of the box."},
      {q:"If you have data that is highly interconnected (e.g., A social network where Users have Friends who have Posts), which is better?",opts:["A. NoSQL Document Store","B. SQL (Relational)","C. Key-Value Store","D. Flat File"],ans:1,exp:"SQL databases are literally designed to handle complex relationships and JOINs efficiently. NoSQL struggles with complex joins."}
    ],
    flows:[
      {title:"Schema vs Schemaless",items:["start:SQL: INSERT User(id:1, name:'Bhoomi', age:25)","proc:SQL: INSERT User(id:2, name:'Alice', pet:'Dog') -> FAILS! 'pet' column doesn't exist!","dec:NoSQL: insert({name:'Bhoomi', age:25})","end:NoSQL: insert({name:'Alice', pet:'Dog'}) -> Succeeds flawlessly!"]}
    ],
    game:{icon:"🗄️",title:"The Architect",desc:"Master database selection",badges:["🗄️ Schema Strict","📄 Document Flexible","⚖️ Scaler"],challenges:[{icon:"📝",title:"Scaling",desc:"Vertical vs Horizontal Scaling?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Data Modeling",badge:"Modeler",desc:"Understand the difference in JSON structure.",tags:["Database","Concepts"],steps:[{title:"SQL Model",desc:"Table 1: User (id, name). Table 2: Address (id, user_id, city)"},{"title:"NoSQL Model",desc:"One Document! {id: 1, name: 'Bhoomi', address: {city: 'NY'}}"},{"title:"Takeaway",desc:"NoSQL embeds related data. SQL links it via Foreign Keys."}],code:`// NoSQL Document (MongoDB)\n{\n  "_id": "5f8a",\n  "name": "Bhoomi",\n  "skills": ["Java", "React", "SQL"], // Array embedded directly!\n  "address": {\n    "city": "Mumbai" // Object embedded directly!\n  }\n}\n// In SQL, 'skills' and 'address' would require 3 separate tables and complex JOINs.`}
  },
  t92: {
    tag:'Phase 2 · Databases', num:92,
    title:'Relational Databases',
    desc:'Storing data in tables (relations) linked by common keys.',
    theory:`<div class="card"><h3>🔗 Connecting the Dots</h3><p>Relational Databases (RDBMS) like PostgreSQL, MySQL, and Oracle use SQL (Structured Query Language) to manage data. The core concept is storing data in 2D grids called <strong>Tables</strong>.</p><h4>Primary and Foreign Keys</h4><ul><li><strong>Primary Key (PK):</strong> A column that uniquely identifies a row in a table (e.g., <code>user_id</code>). It cannot be null and must be unique.</li><li><strong>Foreign Key (FK):</strong> A column in one table that refers to the Primary Key of <em>another</em> table. This creates a link (relationship) between the two tables (e.g., an <code>Order</code> table has a <code>user_id</code> column to know who made the order).</li></ul></div>`,
    mcqs:[
      {q:"What is a Primary Key?",opts:["A. A password to access the database","B. A specific column (or combination of columns) that uniquely identifies every single row in a table","C. The first column in a table","D. A key used for encryption"],ans:1,exp:"Without a Primary Key, you have no way to definitively target a specific row for updates or deletes."},
      {q:"What is a Foreign Key?",opts:["A. A key from a different database","B. A column in Table A that points to the Primary Key in Table B, establishing a relational link between them","C. A key used for foreign languages","D. A temporary key"],ans:1,exp:"Foreign keys are the 'relational' part of a Relational Database."},
      {q:"If an 'Employee' table has a 'department_id' column that acts as a Foreign Key to the 'Department' table, what does this ensure?",opts:["A. Referential Integrity. You cannot insert an Employee with a department_id of 99 if Department 99 does not exist.","B. It makes the database faster","C. It encrypts the department","D. Nothing, it's just a suggestion"],ans:0,exp:"RDBMS enforce strict rules. A foreign key ensures that orphaned data cannot exist."},
      {q:"What SQL command is used to retrieve data from a table?",opts:["A. GET","B. FETCH","C. SELECT","D. PULL"],ans:2,exp:"SELECT is the bread and butter of SQL. e.g., SELECT * FROM users."},
      {q:"What happens if you try to INSERT a new row with a Primary Key that already exists in the table?",opts:["A. It overwrites the old row","B. The database throws a constraint violation error and rejects the insert","C. It assigns a new key automatically","D. It creates a duplicate row"],ans:1,exp:"Primary Keys must be 100% unique."}
    ],
    flows:[
      {title:"Foreign Key Relationship",items:["start:Table: Users (PK: id=5, name='Bhoomi')","proc:Table: Orders (PK: order_id=100)","dec:Orders needs to know WHO bought it","proc:Add FK 'user_id' to Orders","end:Orders (PK: 100, user_id: 5) -> Linked!"]}
    ],
    game:{icon:"🔗",title:"The Relator",desc:"Master tables and keys",badges:["🔗 Linker","🔑 Key Master","🛡️ Integrity Guard"],challenges:[{icon:"📝",title:"Referential Integrity",desc:"What happens if you delete a linked User?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Schema Design",badge:"Table Maker",desc:"Write SQL to create linked tables.",tags:["SQL","Database"],steps:[{title:"Users Table",desc:"CREATE TABLE users (id INT PRIMARY KEY, name VARCHAR)"},{"title:"Orders Table",desc:"CREATE TABLE orders (id INT PRIMARY KEY, amount INT, user_id INT)"},{"title:"Foreign Key",desc:"Add FOREIGN KEY (user_id) REFERENCES users(id)"}],code:`CREATE TABLE users (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  name VARCHAR(100)\n);\n\nCREATE TABLE orders (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  amount DECIMAL(10,2),\n  user_id INT,\n  -- The magical link ensuring referential integrity!\n  FOREIGN KEY (user_id) REFERENCES users(id)\n);`}
  },
  t93: {
    tag:'Phase 2 · Databases', num:93,
    title:'ACID Properties',
    desc:'The four key properties of a transaction that guarantee data validity despite errors, power failures, and other mishaps.',
    theory:`<div class="card"><h3>🛡️ The Ironclad Guarantee</h3><p>Relational Databases (like Postgres) are trusted by banks because they guarantee <strong>ACID</strong> properties for every Transaction.</p><ul><li><strong>Atomicity:</strong> "All or Nothing". A transaction involving 5 SQL queries will completely succeed, or completely rollback if <em>any</em> query fails. No partial data.</li><li><strong>Consistency:</strong> The database rules (Constraints, Foreign Keys) cannot be violated. A transaction will bring the database from one valid state to another valid state.</li><li><strong>Isolation:</strong> If two users buy the last concert ticket at the exact same millisecond, their transactions act as if they are executing sequentially, preventing them from overwriting each other.</li><li><strong>Durability:</strong> Once a transaction says "Success / Committed", the data is safe. Even if someone unplugs the server 1 millisecond later, the data will be there when it reboots.</li></ul></div>`,
    mcqs:[
      {q:"What does the 'A' in ACID stand for and mean?",opts:["A. Asynchronous: It runs in the background","B. Atomicity: The entire transaction is treated as a single, indivisible unit of work. It either completely succeeds or completely fails.","C. Array: It stores data in arrays","D. Available: It is always online"],ans:1,exp:"Atomicity protects against mid-transaction crashes."},
      {q:"What does the 'I' in ACID stand for and mean?",opts:["A. Isolation: Concurrent transactions execute without interfering with each other (e.g., they don't see each other's uncommitted data).","B. Internet: Requires a web connection","C. Integration: Works with other databases","D. Iteration: Loops through data"],ans:0,exp:"Isolation prevents 'Dirty Reads' and race conditions when thousands of users access the database at once."},
      {q:"If a power outage occurs immediately after the database confirms a transaction was committed, which ACID property guarantees the data will still be there when power is restored?",opts:["A. Atomicity","B. Consistency","C. Isolation","D. Durability"],ans:3,exp:"Durability means the commit was physically written to the non-volatile hard drive (or transaction log) before returning success to the user."},
      {q:"What does 'Consistency' ensure in an ACID database?",opts:["A. The database is consistently fast","B. Any transaction will bring the database from one valid state to another valid state, strictly adhering to all defined rules, constraints, and cascades","C. The code looks consistent","D. Backups are consistent"],ans:1,exp:"If a transaction tries to insert a String into an Integer column, it violates consistency and will be rejected."},
      {q:"Do NoSQL databases typically guarantee strict ACID properties?",opts:["A. Yes, always","B. No, many NoSQL databases trade strict ACID guarantees (specifically Consistency) for massive horizontal scalability and speed (BASE properties).","C. Only on Windows","D. Only for JSON data"],ans:1,exp:"MongoDB recently added multi-document ACID transactions, but historically, NoSQL favors 'Eventual Consistency'."}
    ],
    flows:[
      {title:"Atomicity (All or Nothing)",items:["start:BEGIN TRANSACTION","proc:Query 1: Deduct $100 from Alice (Success)","dec:Query 2: Add $100 to Bob (FAILS!)","proc:ROLLBACK triggered!","end:Alice's $100 is refunded. No partial states."]}
    ],
    game:{icon:"🛡️",title:"The Guardian",desc:"Master database integrity",badges:["🛡️ Atomic Shield","🔒 Isolator","💾 Durable Writer"],challenges:[{icon:"📝",title:"Dirty Read",desc:"What happens if Isolation fails?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Mental Walkthrough",badge:"Banker",desc:"Understand why ACID is mandatory for finance.",tags:["Database","ACID"],steps:[{title:"The Scenario",desc:"Alice transfers Bob $50."},{"title:"Atomicity",desc:"If deducting succeeds but adding fails, rollback."},{"title:"Durability",desc:"If server burns down right after success, data survives on disk."}],code:`-- SQL Transaction Example\nBEGIN;\n\nUPDATE accounts SET balance = balance - 50 WHERE name = 'Alice';\n-- If a crash happens right here, the database will \n-- automatically undo Alice's deduction upon reboot (Atomicity).\nUPDATE accounts SET balance = balance + 50 WHERE name = 'Bob';\n\nCOMMIT; -- Now it's Durable!`}
  },
  t94: {
    tag:'Phase 2 · Databases', num:94,
    title:'Normalization',
    desc:'The process of organizing data to minimize redundancy and dependency.',
    theory:`<div class="card"><h3>🧩 The Puzzle Master</h3><p><strong>Normalization</strong> is how you design a Relational Database efficiently. If you store a user's address in every single one of their orders, and they move, you have to update 50 rows! Normalization solves this by splitting data into separate tables and linking them.</p><h4>The Normal Forms</h4><ul><li><strong>1NF (First Normal Form):</strong> Eliminate repeating groups. Every cell must hold a single, atomic value. (No arrays or comma-separated lists in a cell).</li><li><strong>2NF (Second Normal Form):</strong> Must be 1NF. All non-key columns must depend on the <em>entire</em> primary key.</li><li><strong>3NF (Third Normal Form):</strong> Must be 2NF. Eliminate transitive dependencies. (e.g., If a table has <code>Zip_Code</code> and <code>City</code>, <code>City</code> actually depends on <code>Zip_Code</code>, not the Primary Key. So, <code>City</code> and <code>Zip_Code</code> belong in their own separate table!).</li></ul></div>`,
    mcqs:[
      {q:"What is the primary goal of Database Normalization?",opts:["A. To make the database run faster on a single query","B. To reduce data redundancy (duplicate data) and improve data integrity (preventing anomalies when updating/deleting)","C. To convert it to NoSQL","D. To encrypt it"],ans:1,exp:"If a user's address is stored in only ONE place, updating it is easy and safe."},
      {q:"What is the main rule of First Normal Form (1NF)?",opts:["A. Use Foreign Keys","B. Each column must contain atomic (indivisible) values. No arrays, lists, or comma-separated values in a single cell.","C. It must have 3 tables","D. Passwords must be hashed"],ans:1,exp:"If you have a 'skills' column with 'Java, SQL, React', it violates 1NF. It should be broken out into a separate table."},
      {q:"If an 'Orders' table stores 'User_Name' and 'User_Email' alongside the 'Order_Total', what happens if the user changes their email?",opts:["A. It updates automatically","B. You suffer an 'Update Anomaly'. You must find and update every single order that user ever placed. This is why you should Normalize!","C. The database crashes","D. The email is deleted"],ans:1,exp:"In a normalized database, the Orders table would only store 'User_Id'. You would JOIN the User table to get the email."},
      {q:"What is a downside of over-normalizing a database (e.g., 5NF)?",opts:["A. It uses too much hard drive space","B. To retrieve a single piece of useful information, you might have to execute a massive, slow query with 10 different JOINs","C. It crashes the server","D. It deletes data"],ans:1,exp:"Normalization trades Read performance (slower joins) for Write performance (no redundant data to update)."},
      {q:"What is 'Denormalization'?",opts:["A. Deleting the database","B. Intentionally breaking normalization rules (adding redundant data back into a table) to speed up heavy Read operations, avoiding slow JOINs","C. A security flaw","D. Formatting JSON"],ans:1,exp:"Data warehouses often use Denormalization because they prioritize read speed over write efficiency."}
    ],
    flows:[
      {title:"1NF Violation Fix",items:["start:Table: User(id:1, skills:'Java, C++')","proc:Violates 1NF! (Atomic values)","proc:Create Table: UserSkills(user_id, skill)","dec:Insert(1, 'Java')","end:Insert(1, 'C++'). 1NF Achieved!"]}
    ],
    game:{icon:"🧩",title:"The Organizer",desc:"Master data structures",badges:["🧩 1NF Atom Smasher","✂️ Redundancy Cutter","🚄 Denormalizer"],challenges:[{icon:"📝",title:"Update Anomaly",desc:"Explain why redundant data is bad",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Normalizing 3NF",badge:"Architect",desc:"Mentally break apart a bad table.",tags:["Database","Theory"],steps:[{title:"Bad Table",desc:"Employees (id, name, dept_id, dept_name)"},{"title:"The Flaw",desc:"dept_name depends on dept_id, not employee id (3NF violation)"},{"title:"The Fix",desc:"Create Departments table (dept_id, dept_name)"}],code:`-- BAD (Unnormalized)\nCREATE TABLE employees (\n  id INT PRIMARY KEY,\n  name VARCHAR(50),\n  dept_id INT,\n  dept_name VARCHAR(50) -- Redundant! Will be duplicated on every employee in that dept.\n);\n\n-- GOOD (Normalized to 3NF)\nCREATE TABLE departments (id INT PRIMARY KEY, name VARCHAR(50));\nCREATE TABLE employees (id INT PRIMARY KEY, name VARCHAR(50), dept_id INT);`}
  },
  t95: {
    tag:'Phase 2 · Databases', num:95,
    title:'Indexes',
    desc:'A data structure that improves the speed of data retrieval operations on a database table.',
    theory:`<div class="card"><h3>📖 The Table of Contents</h3><p>If you want to find a chapter in a 1000-page book, you don't flip through every single page (a <strong>Full Table Scan</strong>). You look at the Table of Contents, find the exact page, and jump straight to it. That is exactly what a Database <strong>Index</strong> is.</p><h4>How it works</h4><p>When you create an Index on a column (e.g., <code>email</code>), the database creates a separate, hidden data structure (usually a <strong>B-Tree</strong>) that keeps those emails perfectly sorted. Searching a B-Tree is <code>O(log N)</code>, which is lightning fast compared to scanning the whole table <code>O(N)</code>.</p><div class="box b-ro"><h5>⚠️ The Cost of Indexes</h5><p>Indexes drastically speed up <em>Reads</em> (SELECT). However, they slow down <em>Writes</em> (INSERT/UPDATE/DELETE). Every time you insert a new row, the database must also update and rebalance the hidden Index B-Tree.</p></div></div>`,
    mcqs:[
      {q:"What is the purpose of a Database Index?",opts:["A. To compress the data","B. To dramatically speed up data retrieval (SELECT queries) by avoiding full table scans","C. To encrypt passwords","D. To link two tables together"],ans:1,exp:"Without an index, finding a user by email in a 1-million-row table requires checking every single row."},
      {q:"What underlying data structure is most commonly used by relational databases to implement Indexes?",opts:["A. Array","B. Linked List","C. B-Tree (Balanced Tree)","D. Stack"],ans:2,exp:"B-Trees keep data sorted and perfectly balanced, allowing for O(log N) search times."},
      {q:"If Indexes make reading data so fast, why don't we just Index every single column in the database?",opts:["A. It is illegal","B. Because Indexes take up hard drive space, and they SLOW DOWN write operations (Inserts/Updates/Deletes) because the index tree must be updated every time the table changes","C. It makes the database crash","D. The CPU can't handle it"],ans:1,exp:"Indexing is a trade-off. You index columns you search frequently (like email or username), but ignore columns you don't (like bio)."},
      {q:"Does a Primary Key column have an index?",opts:["A. No","B. Yes, databases automatically create a unique Index on the Primary Key column","C. Only in MySQL","D. Only if you manually create it"],ans:1,exp:"Because you almost always query by ID, the DB indexes it for you by default."},
      {q:"What happens if you run a query using a 'LIKE %search%' wildcard at the BEGINNING of a string (e.g. WHERE name LIKE '%omi')?",opts:["A. The index makes it instant","B. The database CANNOT use the index (because it's sorted alphabetically from the start of the string), resulting in a slow Full Table Scan","C. The query crashes","D. It uses a HashMap"],ans:1,exp:"Indexes are like phonebooks. If you know the last name starts with 'S', you jump to 'S'. If you only know the name *ends* with 'S', the phonebook is useless."}
    ],
    flows:[
      {title:"Full Scan vs Index",items:["start:SELECT * FROM users WHERE email='a@a.com'","dec:Is 'email' indexed?","proc:(No) Full Table Scan! Checks 1,000,000 rows. Slow!","dec:(Yes) Binary Search the B-Tree Index","end:Jumps straight to row in 20 steps. Instant!"]}
    ],
    game:{icon:"📖",title:"The Librarian",desc:"Master fast lookups",badges:["📖 Table of Contents","🌳 B-Tree Climber","📉 O(N) Eliminator"],challenges:[{icon:"📝",title:"The Trade-off",desc:"Why does indexing slow down INSERTS?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Create an Index",badge:"Speedster",desc:"Speed up a slow query.",tags:["SQL","Database"],steps:[{title:"The Problem",desc:"SELECT * FROM users WHERE last_name = 'Smith' is slow."},{"title:"The Solution",desc:"CREATE INDEX idx_lastname ON users(last_name);"},{"title:"The Result",desc:"Query now runs in 1ms instead of 500ms."}],code:`-- Creating a table\nCREATE TABLE users (id INT PRIMARY KEY, last_name VARCHAR(50));\n\n-- By default, searching by last_name requires a Full Table Scan.\n\n-- Add an index to speed it up:\nCREATE INDEX idx_last_name ON users(last_name);\n\n-- Now, the database uses a B-Tree to find 'Smith' instantly.`}
  },
"""

start_marker = "};\n\nlet userXP"
inject_idx = content.find(start_marker)

if inject_idx != -1:
    new_content = content[:inject_idx] + ",\n" + rich_content + content[inject_idx:]
    with open(html_path, "w") as f:
        f.write(new_content)
    print("Successfully generated T91-T95 rich content!")
else:
    print("Could not find injection point.")
