import re

html_path = "/Users/bhoomim/devops CI:CD/handbook/fullstack_ai_handbook.html"
with open(html_path, "r") as f:
    content = f.read()

rich_content = r"""
  t84: {
    tag:'Phase 2 · Architecture', num:84,
    title:'Microservices Architecture',
    desc:'An architectural style that structures an application as a collection of loosely coupled, independently deployable services.',
    theory:`<div class="card"><h3>🏙️ The City of Services</h3><p>Instead of building one giant application that does everything (Auth, Payments, Inventory, Shipping), a <strong>Microservices Architecture</strong> breaks the application down into tiny, specialized applications.</p><h4>The Philosophy</h4><ul><li><strong>Single Responsibility:</strong> Each microservice does exactly one thing well (e.g., The Payment Service <em>only</em> processes payments).</li><li><strong>Independent Deployment:</strong> You can update and deploy the Payment Service without rebooting or touching the Inventory Service.</li><li><strong>Decentralized Data:</strong> Each microservice has its <em>own</em> database. They are forbidden from reading each other's databases directly. They must communicate via APIs.</li></ul></div>`,
    mcqs:[
      {q:"What is a core tenet of Microservices Architecture regarding databases?",opts:["A. All microservices must share one giant master database","B. Each microservice should own its own database to prevent tight data coupling","C. Microservices do not use databases","D. They all share a single Redis cache"],ans:1,exp:"If the Inventory DB schema changes, the Payment service shouldn't crash. Loose coupling is paramount."},
      {q:"How do Microservices typically communicate with each other?",opts:["A. By reading each other's memory","B. Via HTTP REST APIs, gRPC, or asynchronous Message Brokers (like Kafka)","C. By directly querying each other's databases","D. They don't communicate"],ans:1,exp:"They act like completely separate companies talking over the network."},
      {q:"What does 'Independent Deployability' mean?",opts:["A. You can only deploy on Independence Day","B. If a team updates the Auth Service, they can deploy it to production instantly without coordinating with the Payments team or taking down the whole system","C. The code deploys itself","D. You don't need servers"],ans:1,exp:"This massively increases organizational agility and release cadence for large tech companies."},
      {q:"Is Microservices Architecture a silver bullet that everyone should use?",opts:["A. Yes, monoliths are obsolete","B. No, microservices introduce massive operational complexity (network latency, distributed tracing, complex deployments). If you are a small startup, build a monolith first.","C. Yes, it makes code run faster","D. Only for Java apps"],ans:1,exp:"Microservices solve organizational scaling problems, not performance problems. They often make performance worse due to network hops."},
      {q:"Which Spring project provides a robust toolkit for building and orchestrating Microservices?",opts:["A. Spring MVC","B. Spring Data","C. Spring Cloud (Netflix OSS, Eureka, Zuul)","D. Spring Security"],ans:2,exp:"Spring Cloud handles service discovery, configuration, and circuit breaking automatically."}
    ],
    flows:[
      {title:"Microservice Communication",items:["start:User clicks 'Checkout'","proc:Order Service receives HTTP req","proc:Order Service calls Payment Service API","proc:Payment Service calls Bank API","end:Payment returns success to Order"]}
    ],
    game:{icon:"🏙️",title:"The City Planner",desc:"Master distributed systems",badges:["🏙️ Micro Manager","🔗 Decoupler","🚀 Indie Deployer"],challenges:[{icon:"📝",title:"Decentralized Data",desc:"Why not share one DB?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Architectural Diagram",badge:"Architect",desc:"Visualize a microservice layout.",tags:["Architecture","Concepts"],steps:[{title:"Frontend",desc:"React App -> API Gateway"},{"title:"Services",desc:"Auth Service (Postgres), Cart Service (Redis)"},{"title:"Communication",desc:"Services talk via REST or Kafka"}],code:`// Conceptual Microservice Layout\n// [Client App]\n//      |\n// [API Gateway]\n//    /   \\   \\\n// [Auth] [Cart] [Payment]\n//   |      |       |\n// (SQL) (Redis)  (Stripe API)`}
  },
  t85: {
    tag:'Phase 2 · Architecture', num:85,
    title:'Monolith vs Microservices',
    desc:'Understanding the trade-offs between a single unified codebase and distributed services.',
    theory:`<div class="card"><h3>⚖️ The Great Debate</h3><p>A <strong>Monolith</strong> is a single, massive codebase where all modules (Auth, Payments, Inventory) run in the exact same process and share the same memory and database.</p><h4>Monolith Pros & Cons</h4><ul><li>👍 <strong>Simple:</strong> Easy to debug, easy to test, no network latency between modules.</li><li>👎 <strong>Scaling:</strong> If the Payment module needs more CPU, you have to scale the <em>entire</em> massive monolith. You can't scale modules independently.</li></ul><h4>Microservices Pros & Cons</h4><ul><li>👍 <strong>Scaling:</strong> You can spin up 100 instances of the Payment Service, and only 2 instances of the Inventory Service.</li><li>👎 <strong>Complex:</strong> "Distributed Monolith" anti-pattern. If a network call fails, how do you trace the bug across 5 different services? (Requires advanced Observability).</li></ul></div>`,
    mcqs:[
      {q:"What is a Monolithic Architecture?",opts:["A. An app built of stone","B. An application where all business capabilities are bundled into a single codebase and deployed as a single executable/process","C. A front-end framework","D. A database pattern"],ans:1,exp:"A standard Ruby on Rails, Django, or Spring Boot app starting out is almost always a monolith."},
      {q:"If your application is experiencing heavy traffic ONLY on the 'Image Processing' feature, what happens in a Monolith?",opts:["A. Only the image module scales up","B. You must duplicate and scale the ENTIRE massive application (including Auth, Payments, etc.) across multiple servers just to handle the image load","C. The database crashes","D. Nothing happens"],ans:1,exp:"This is resource inefficient. Microservices solve this by letting you scale ONLY the Image Processing service."},
      {q:"What is a major difficulty introduced by Microservices that Monoliths do not have?",opts:["A. Code size","B. Distributed transactions and network latency. (e.g. What happens if Service A updates its DB, calls Service B, but the network drops?)","C. Language limitations","D. UI design"],ans:1,exp:"Handling distributed state and network failures is incredibly difficult."},
      {q:"When is a Monolith actually the better choice?",opts:["A. For massive companies like Netflix or Uber","B. For small to medium teams building a new product (MVP) where fast iteration and simplicity are more important than independent scalability","C. Never","D. For AI apps"],ans:1,exp:"Martin Fowler recommends starting with a Monolith and only extracting Microservices when the monolith becomes too painful to manage (The Strangler Pattern)."},
      {q:"What is the 'Strangler Fig Pattern'?",opts:["A. A sorting algorithm","B. A strategy to migrate a Monolith to Microservices by gradually replacing specific pieces of functionality with new microservices until the monolith is dead","C. A security attack","D. A UI pattern"],ans:1,exp:"You don't rewrite the whole app. You slowly strangle the monolith one feature at a time."}
    ],
    flows:[
      {title:"Scaling Differences",items:["start:Traffic Spikes on 'Search'","dec:Monolith?","proc:Spin up 5 entire App Clones","dec:Microservices?","end:Spin up 5 'Search Services' only. Efficient!"]}
    ],
    game:{icon:"⚖️",title:"The Judge",desc:"Master architectural trade-offs",badges:["⚖️ Trade-off Analyst","🧱 Monolith Defender","🌿 Strangler Fig"],challenges:[{icon:"📝",title:"The Strangler",desc:"Explain the Strangler Pattern",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Cost Analysis",badge:"CTO",desc:"Identify when to switch to microservices.",tags:["Architecture","Theory"],steps:[{title:"Phase 1: Startup",desc:"Build Monolith. Easy to deploy, one database."},{"title:"Phase 2: Pain",desc:"100 devs working in one codebase causes constant merge conflicts."},{"title:"Phase 3: Microservices",desc:"Split teams into Auth, Billing, Cart. Deploy independently."}],code:`// Code doesn't solve this; Architecture does.\n// Start Monolith -> Hit scaling/org pain -> Extract Services.\n// Don't start with Microservices unless you have Google's budget!`}
  },
  t86: {
    tag:'Phase 2 · Architecture', num:86,
    title:'API Gateway',
    desc:'The single entry point for all client requests in a microservices architecture.',
    theory:`<div class="card"><h3>🚪 The Front Door</h3><p>If you have 50 different microservices, a mobile app shouldn't have to memorize 50 different IP addresses to fetch data. An <strong>API Gateway</strong> sits between the clients (Web/Mobile) and the backend microservices.</p><h4>Gateway Responsibilities</h4><ul><li><strong>Routing:</strong> Receives a request to <code>/api/payment</code> and routes it to the internal Payment Service IP.</li><li><strong>Cross-Cutting Concerns:</strong> Handles Authentication, SSL termination, and Rate Limiting centrally so every microservice doesn't have to duplicate that logic.</li><li><strong>Aggregation:</strong> Instead of the client making 3 requests to get User, Cart, and Recommendations, the Gateway can make those 3 internal requests, aggregate the JSON, and return it to the client in 1 network hop.</li></ul></div>`,
    mcqs:[
      {q:"What is the primary role of an API Gateway?",opts:["A. To host the database","B. To act as a single entry point (reverse proxy) that routes incoming client requests to the correct internal microservice","C. To render HTML","D. To store passwords"],ans:1,exp:"Clients only ever talk to the Gateway. The internal network of microservices remains hidden and secure."},
      {q:"Without an API Gateway, what major problem would a mobile app face in a microservices architecture?",opts:["A. It couldn't use HTTPS","B. It would have to make dozens of separate network calls to different service IP addresses, crushing battery life and performance","C. It would crash","D. It couldn't use JSON"],ans:1,exp:"API Gateways can perform 'API Composition', fetching data from multiple services and returning it to the mobile app in one swift response."},
      {q:"Which of the following is a 'Cross-Cutting Concern' that is perfectly handled by an API Gateway?",opts:["A. Calculating tax on a shopping cart","B. Verifying JWT Authentication tokens and enforcing Rate Limiting before letting traffic into the internal network","C. Updating user profiles","D. Sending emails"],ans:1,exp:"If the Gateway handles Auth, your 50 microservices don't have to write their own Auth logic! They trust the Gateway."},
      {q:"What happens if the API Gateway goes offline?",opts:["A. Nothing, the app still works","B. The entire system becomes inaccessible to the outside world (Single Point of Failure)","C. The database deletes itself","D. It automatically restarts"],ans:1,exp:"Because it's a SPOF, API Gateways must be highly available, clustered, and load-balanced."},
      {q:"Which of these is a popular open-source API Gateway?",opts:["A. Spring Cloud Gateway (or Kong, NGINX)","B. React","C. PostgreSQL","D. Kafka"],ans:0,exp:"Spring Cloud Gateway handles dynamic routing and filters specifically for Spring ecosystems."}
    ],
    flows:[
      {title:"API Aggregation Flow",items:["start:Mobile App requests 'Profile Dashboard'","proc:Gateway receives request","proc:Gateway calls Auth Service, Order Service in parallel","dec:Gateway merges responses","end:Gateway returns one massive JSON payload to Mobile"]}
    ],
    game:{icon:"🚪",title:"The Bouncer",desc:"Master API Gateways",badges:["🚪 The Front Door","🛡️ Rate Limiter","🧩 Aggregator"],challenges:[{icon:"📝",title:"Cross-Cutting",desc:"Name 2 Cross-Cutting concerns",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Gateway Routing (Mental)",badge:"Traffic Cop",desc:"Configure routing rules for a gateway.",tags:["Architecture","Gateway"],steps:[{title:"Match Path",desc:"If path starts with /api/billing"},{"title:"Strip Prefix",desc:"Remove /api before forwarding"},{"title:"Forward",desc:"Send to internal IP: 10.0.0.5:8080"}],code:`// Conceptual Gateway Configuration (YAML style)\n/*\nroutes:\n  - id: billing-service\n    uri: http://internal-billing-ip:8080\n    predicates:\n      - Path=/api/billing/**\n    filters:\n      - RateLimit=100_per_second\n      - JwtAuthCheck\n*/`}
  },
  t87: {
    tag:'Phase 2 · Architecture', num:87,
    title:'Service Discovery',
    desc:'How microservices find each other dynamically on a network without hardcoded IP addresses.',
    theory:`<div class="card"><h3>🗺️ The Phonebook</h3><p>In the cloud (AWS/GCP), microservices are constantly dying and spinning back up. Their IP addresses change constantly. If Service A wants to call Service B, it cannot rely on a hardcoded IP address like <code>192.168.1.5</code>. It needs <strong>Service Discovery</strong>.</p><h4>The Service Registry (e.g., Eureka)</h4><p>A Service Registry acts like a dynamic phonebook.</p><ol><li>When a microservice boots up, it pings the Registry: <em>"Hi, I'm the Payment Service, my current IP is 10.0.0.9."</em></li><li>When the Order Service needs to call Payments, it asks the Registry: <em>"Give me an IP for the Payment Service."</em></li><li>The Registry hands over a live IP, and the Order service makes the HTTP call.</li></ol></div>`,
    mcqs:[
      {q:"Why are hardcoded IP addresses dangerous in a cloud-based Microservices architecture?",opts:["A. They are too long","B. Because cloud servers (like Docker containers/Kubernetes pods) are ephemeral; they die and restart frequently with entirely new IP addresses","C. They use too much memory","D. They are easily hacked"],ans:1,exp:"You need a dynamic way to resolve names (like 'payment-service') to their current live IPs."},
      {q:"What is a Service Registry?",opts:["A. A government database","B. A dedicated server (like Netflix Eureka or HashiCorp Consul) that maintains a live, continuously updated list of all active microservices and their current IP addresses","C. A caching layer","D. A load balancer"],ans:1,exp:"It acts exactly like DNS, but for internal microservices."},
      {q:"What is the 'Heartbeat' mechanism in Service Discovery?",opts:["A. A health check feature","B. Microservices constantly send a 'heartbeat' ping (e.g. every 30s) to the Registry to say 'I am still alive'. If the Registry misses a few heartbeats, it removes that instance from the phonebook.","C. It measures CPU usage","D. It syncs databases"],ans:1,exp:"This ensures the Registry doesn't hand out IP addresses of dead servers."},
      {q:"What is Client-Side Load Balancing (e.g., Spring Cloud LoadBalancer / Ribbon)?",opts:["A. The browser balances the load","B. The caller asks the Registry for ALL IPs of a service, and then mathematically picks one (Round Robin) to spread the traffic out itself","C. A hardware router","D. The database balances it"],ans:1,exp:"Instead of a central hardware load balancer bottleneck, the clients do the balancing themselves."},
      {q:"What happens if the Service Registry crashes?",opts:["A. All communication instantly fails","B. Usually, microservices cache the 'phonebook' locally. They can continue to communicate using their cached IPs until the Registry comes back online.","C. The database deletes itself","D. The cloud reboots"],ans:1,exp:"Caching prevents the Registry from being a catastrophic Single Point of Failure."}
    ],
    flows:[
      {title:"Service Discovery Flow",items:["start:Payment API boots up","proc:Registers with Eureka (IP: 10.5)","proc:Order API asks Eureka for 'Payment'","dec:Eureka returns '10.5'","end:Order API calls 10.5 directly"]}
    ],
    game:{icon:"🗺️",title:"The Operator",desc:"Master dynamic networking",badges:["🗺️ Phonebook Keeper","💓 Heartbeat Monitor","⚖️ Client Balancer"],challenges:[{icon:"📝",title:"Heartbeats",desc:"Explain why heartbeats are needed",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Eureka Client",badge:"Registrant",desc:"Annotate a Spring app to use Discovery.",tags:["Spring","Cloud"],steps:[{title:"Dependency",desc:"Add spring-cloud-starter-netflix-eureka-client"},{"title:"Annotation",desc:"Add @EnableDiscoveryClient to main class"},{"title:"Config",desc:"Set spring.application.name=billing-service"}],code:`import org.springframework.cloud.client.discovery.EnableDiscoveryClient;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\n@EnableDiscoveryClient // Tells this app to register with the Eureka Phonebook\npublic class BillingServiceApplication {\n  public static void main(String[] args) {\n    SpringApplication.run(BillingServiceApplication.class, args);\n  }\n}`}
  },
  t88: {
    tag:'Phase 2 · Architecture', num:88,
    title:'Circuit Breaker',
    desc:'A design pattern used in modern software development to prevent catastrophic cascading failures across distributed systems.',
    theory:`<div class="card"><h3>🔌 Preventing Cascading Failures</h3><p>In Microservices, Service A calls Service B, which calls Service C. What happens if Service C crashes? Service B hangs waiting for a response, locking up its threads. Then Service A hangs waiting for B. Within seconds, your entire architecture crashes. This is a <strong>Cascading Failure</strong>.</p><h4>The Circuit Breaker Pattern</h4><p>Just like an electrical circuit breaker in your house, a software Circuit Breaker (like <em>Resilience4j</em>) wraps the network call. If it detects a high failure rate or timeout, it <strong>"Trips" (Opens)</strong> the circuit. Subsequent calls immediately fail fast or return a fallback default value without even trying to make the network call, giving Service C time to recover.</p></div>`,
    mcqs:[
      {q:"What is a Cascading Failure?",opts:["A. A UI bug","B. A failure in one microservice that causes threads/resources to lock up in calling microservices, eventually taking down the entire system","C. A database deletion","D. A memory leak"],ans:1,exp:"Because microservices rely on each other, a single slow service acts like a traffic jam backing up the whole city."},
      {q:"What does a Circuit Breaker do when it is in the 'OPEN' state?",opts:["A. It allows all traffic through","B. It immediately blocks the network call and returns an error or a Fallback response, preventing the caller from wasting time/threads waiting for a dead service","C. It opens a database connection","D. It restarts the server"],ans:1,exp:"'Open' means the electrical circuit is broken. Traffic cannot flow."},
      {q:"What does a Circuit Breaker do in the 'HALF-OPEN' state?",opts:["A. It crashes","B. It allows a small percentage of test traffic through to see if the failing service has recovered. If successful, it CLOSES. If it fails, it OPENS again.","C. It cuts the bandwidth in half","D. It only allows GET requests"],ans:1,exp:"This is the self-healing mechanism of modern cloud architecture."},
      {q:"What is a 'Fallback Method'?",opts:["A. A method that deletes data","B. A backup method that executes if the Circuit Breaker is OPEN, providing a default response (e.g., returning cached data instead of live data) so the user doesn't see an error","C. A method that loops forever","D. A UI component"],ans:1,exp:"If the Recommendation Engine is down, the fallback method just returns a hardcoded list of 'Top 10 Global Movies' instead of crashing the page."},
      {q:"Which library is the modern standard for Circuit Breaking in Java/Spring?",opts:["A. Netflix Hystrix (Deprecated)","B. Resilience4j","C. Log4j","D. Jackson"],ans:1,exp:"Resilience4j is a lightweight, easy-to-use fault tolerance library inspired by Hystrix."}
    ],
    flows:[
      {title:"Circuit Breaker States",items:["start:CLOSED (Traffic Flows Normal)","proc:Errors > 50%? -> Trips to OPEN","proc:OPEN (All calls instantly fail/fallback)","dec:Wait 30s -> HALF-OPEN (Test)","proc:Test Succeeds -> CLOSED","end:Test Fails -> OPEN"]}
    ],
    game:{icon:"🔌",title:"The Electrician",desc:"Master fault tolerance",badges:["🔌 Circuit Breaker","🚑 Fallback Paramedic","🩹 Self Healer"],challenges:[{icon:"📝",title:"Half-Open",desc:"Explain the Half-Open state",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Fallback Logic",badge:"Safety Net",desc:"Configure a Resilience4j fallback method.",tags:["Architecture","Spring"],steps:[{title:"Annotation",desc:"@CircuitBreaker(name='billing', fallbackMethod='backup')"},{"title:"Main Method",desc:"Attempt risky HTTP call to billing service"},{"title:"Fallback",desc:"If it fails, backup() returns 'Service Unavailable' cleanly"}],code:`@Service\npublic class BillingClient {\n\n  @CircuitBreaker(name = "billingService", fallbackMethod = "defaultBilling")\n  public String getBillingInfo() {\n    // Risky HTTP call that might timeout/fail\n    return restTemplate.getForObject("http://billing/info", String.class);\n  }\n\n  // This runs instantly if the Circuit is OPEN, preventing app crash!\n  public String defaultBilling(Exception e) {\n    return "Billing currently unavailable. Please try again later.";\n  }\n}`}
  },
  t89: {
    tag:'Phase 2 · Architecture', num:89,
    title:'Message Brokers',
    desc:'Middleware that enables asynchronous communication between microservices.',
    theory:`<div class="card"><h3>📨 The Post Office</h3><p>If the Order Service calls the Shipping Service via HTTP REST, it's <strong>Synchronous</strong>. The Order Service has to wait for a response. If Shipping is offline, Order fails. This is tight coupling.</p><h4>Asynchronous Messaging (Kafka / RabbitMQ)</h4><p>Instead of direct calls, the Order Service drops a message (an Event) into a <strong>Message Broker</strong>: <em>"Order #123 was created!"</em> and immediately responds to the user. <br>The Shipping Service acts as a Consumer. It listens to the Broker, pulls the message, and processes it whenever it has free time.</p><div class="box b-cy"><h5>Benefits</h5><p>Even if Shipping crashes for 2 hours, the Order Service keeps running perfectly. The messages just pile up safely in the Broker. When Shipping reboots, it processes the backlog.</p></div></div>`,
    mcqs:[
      {q:"What is the primary difference between a REST API call and a Message Broker (Kafka/RabbitMQ) call?",opts:["A. REST is async, Brokers are sync","B. REST is Synchronous (wait for response). Brokers enable Asynchronous communication (fire and forget), decoupling the services in time.","C. REST uses JSON, Brokers use XML","D. They are identical"],ans:1,exp:"Decoupling in time means the receiving service doesn't even have to be online when the message is sent!"},
      {q:"In a Pub/Sub (Publish/Subscribe) model, who knows about the Consumers?",opts:["A. The Publisher","B. Nobody. The Publisher just drops the message into a Topic. It doesn't know or care if 0, 1, or 100 Consumers are listening to that Topic.","C. The Database","D. The User"],ans:1,exp:"This enables massive scalability. You can add a new 'Notification Service' consumer tomorrow without changing a single line of code in the Order Service."},
      {q:"What happens if a Consumer microservice crashes while a Publisher is sending messages to the Broker?",opts:["A. The Publisher crashes","B. The messages are lost forever","C. The messages are safely queued/stored in the Broker. When the Consumer reboots, it picks up exactly where it left off.","D. The Broker crashes"],ans:2,exp:"This provides incredible system resilience and fault tolerance."},
      {q:"Which of these is a distributed, high-throughput Event Streaming platform (excellent for big data and logs)?",opts:["A. Redis","B. Apache Kafka","C. MySQL","D. Tomcat"],ans:1,exp:"Kafka is designed for massive scale and event replay. RabbitMQ is better for complex, targeted message routing."},
      {q:"What is a 'Topic' in Kafka?",opts:["A. A UI theme","B. A named channel or category to which messages are published (e.g., 'orders-topic')","C. A database table","D. A security protocol"],ans:1,exp:"Producers publish to a Topic. Consumers subscribe to a Topic."}
    ],
    flows:[
      {title:"Pub/Sub Decoupling",items:["start:OrderService (Publisher)","proc:Publishes 'OrderCreated' to Kafka Topic","dec:Kafka holds the Event","proc:EmailService (Sub) reads it -> Sends Email","end:ShippingService (Sub) reads it -> Ships Item"]}
    ],
    game:{icon:"📨",title:"The Postmaster",desc:"Master async messaging",badges:["📨 Publisher","👂 Subscriber","⏳ Async Master"],challenges:[{icon:"📝",title:"Sync vs Async",desc:"Explain the difference in coupling",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Pub/Sub Concept",badge:"Broadcaster",desc:"Understand how to publish and consume events.",tags:["Architecture","Kafka"],steps:[{title:"Producer",desc:"kafkaTemplate.send('orders', newOrder)"},{"title:"Broker",desc:"Kafka safely stores the JSON message"},{"title:"Consumer",desc:"@KafkaListener(topics = 'orders') to process it"}],code:`// PRODUCER (Order Service)\npublic void placeOrder(Order order) {\n  // Fire and forget! No waiting for HTTP responses.\n  kafkaTemplate.send("order-topic", order);\n}\n\n// CONSUMER (Shipping Service)\n// Listens in the background. Triggered when a message arrives.\n@KafkaListener(topics = "order-topic")\npublic void processShipping(Order order) {\n  shippingEngine.ship(order);\n}`}
  },
  t90: {
    tag:'Phase 2 · Architecture', num:90,
    title:'Event-Driven Architecture',
    desc:'A software architecture paradigm promoting the production, detection, and consumption of events.',
    theory:`<div class="card"><h3>🎭 Action and Reaction</h3><p>Taking Message Brokers a step further, <strong>Event-Driven Architecture (EDA)</strong> designs the entire system around "Events" (things that have happened in the past). Instead of sending commands ("Update the Database"), services emit facts ("User Registered").</p><h4>Event Sourcing</h4><p>In traditional databases, you only store the <em>current state</em> (e.g., Balance: $50). In Event Sourcing, you store <strong>every event that ever happened</strong> as an immutable log (Deposited $100, Withdrew $50). The current balance is calculated by replaying the events! This provides a flawless audit trail.</p><h4>CQRS</h4><p>Command Query Responsibility Segregation. You physically separate the API that <em>Writes</em> data (Commands) from the API that <em>Reads</em> data (Queries), often using entirely different databases optimized for each task.</p></div>`,
    mcqs:[
      {q:"What is the defining characteristic of an 'Event' in EDA?",opts:["A. It is a request to do something in the future","B. It is a factual statement about something that has ALREADY happened in the past (e.g., 'OrderShippedEvent'). It is immutable.","C. It is an error log","D. It is an HTML file"],ans:1,exp:"Because it happened in the past, it cannot be changed. Other services simply react to this fact."},
      {q:"What does Event Sourcing do instead of storing the current state of an entity in a SQL table?",opts:["A. It deletes the state","B. It stores a sequential, immutable log of every event/action that has ever occurred. Current state is derived by replaying the log.","C. It stores data in memory only","D. It uses Blockchain"],ans:1,exp:"If a bank database corrupts, Event Sourcing allows them to rebuild the exact balance by replaying every deposit and withdrawal from the beginning of time."},
      {q:"What does CQRS stand for?",opts:["A. Code Query Request System","B. Command Query Responsibility Segregation","C. Central Query Routing Service","D. Create Query Read Save"],ans:1,exp:"Commands alter state (Writes). Queries request data (Reads)."},
      {q:"Why would an architect use CQRS?",opts:["A. To make the code smaller","B. Because in large systems, Reads outnumber Writes 100 to 1. CQRS allows you to scale the Read database (e.g. ElasticSearch) completely independently of the Write database (e.g. PostgreSQL).","C. To avoid using APIs","D. To save money on servers"],ans:1,exp:"It optimizes performance for complex systems by separating the heavy write logic from the fast read logic."},
      {q:"What is 'Eventual Consistency'?",opts:["A. The database is instantly perfectly synced","B. The reality in distributed EDA systems that when a Write occurs, it might take a few milliseconds (or seconds) for that event to propagate to the Read databases. They will be consistent 'eventually'.","C. Never being consistent","D. A Java library"],ans:1,exp:"If you update your Facebook profile, your friend might still see the old profile for 2 seconds. This is acceptable eventual consistency."}
    ],
    flows:[
      {title:"CQRS & Event Sourcing",items:["start:User Sends POST (Command)","proc:Command API validates, writes 'Event' to Kafka","dec:Read API (ElasticSearch) consumes Event","proc:Updates its denormalized view","end:User Sends GET (Query) -> Super fast read!"]}
    ],
    game:{icon:"🎭",title:"The Reactor",desc:"Master event-driven design",badges:["🎭 Reactor","📜 Event Sourcer","⚖️ CQRS Splitter"],challenges:[{icon:"📝",title:"Eventual Consistency",desc:"Is it acceptable for a bank?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Event Object",badge:"Historian",desc:"Design an immutable Event object.",tags:["Architecture","Events"],steps:[{title:"Immutable",desc:"Make fields final, no setters"},{"title:"Past Tense",desc:"Name it 'UserRegisteredEvent'"},{"title:"Payload",desc:"Include timestamp and relevant data"}],code:`// Events must be immutable facts about the past.\npublic class UserRegisteredEvent {\n  private final String userId;\n  private final long timestamp;\n\n  public UserRegisteredEvent(String userId) {\n    this.userId = userId;\n    this.timestamp = System.currentTimeMillis();\n  }\n  // Getters only. NO Setters!\n}`}
  },
"""

start_marker = "};\n\nlet userXP"
inject_idx = content.find(start_marker)

if inject_idx != -1:
    new_content = content[:inject_idx] + ",\n" + rich_content + content[inject_idx:]
    with open(html_path, "w") as f:
        f.write(new_content)
    print("Successfully generated T84-T90 rich content!")
else:
    print("Could not find injection point.")
