import re

html_path = "/Users/bhoomim/devops CI:CD/handbook/fullstack_ai_handbook.html"
with open(html_path, "r") as f:
    content = f.read()

rich_content = r"""
  t101: {
    tag:'Phase 3 · Frontend', num:101,
    title:'HTML5 Semantics',
    desc:'Using tags that carry meaning to improve accessibility and SEO.',
    theory:`<div class="card"><h3>🏗️ Meaningful Structure</h3><p>Before HTML5, websites were built using endless <code>&lt;div&gt;</code> tags (div soup). A screen reader for a blind user, or a Google Search bot, couldn't tell if a div was the main article or just a sidebar.</p><h4>Semantic Tags</h4><p><strong>Semantic HTML</strong> introduces tags that describe their meaning to both the browser and the developer.</p><ul><li><code>&lt;header&gt;</code>: Introductory content or navigation links.</li><li><code>&lt;main&gt;</code>: The dominant content of the page. Should be unique.</li><li><code>&lt;article&gt;</code>: A self-contained composition (like a blog post or news story).</li><li><code>&lt;nav&gt;</code>: Navigation menus.</li><li><code>&lt;section&gt;</code>: A thematic grouping of content.</li></ul></div>`,
    mcqs:[
      {q:"What is the primary benefit of using Semantic HTML tags instead of regular <div> tags?",opts:["A. They automatically add CSS styling","B. They provide meaning to the structure, drastically improving Accessibility (screen readers) and SEO (Search Engine Optimization)","C. They make the code run faster","D. They prevent JavaScript errors"],ans:1,exp:"A screen reader knows how to jump straight to the <main> tag, bypassing repetitive header navigation."},
      {q:"Which tag should contain the core, unique content of the document?",opts:["A. <section>","B. <body>","C. <main>","D. <article>"],ans:2,exp:"There should only be one <main> tag visible on a page at a time."},
      {q:"If you are building a list of links to jump to different pages on your site, which tag should wrap them?",opts:["A. <ul>","B. <nav>","C. <menu>","D. <header>"],ans:1,exp:"<nav> tells bots and screen readers 'Hey, this is the main navigation block!'"},
      {q:"What is the difference between <article> and <section>?",opts:["A. There is no difference","B. <article> is for self-contained content that makes sense on its own (like a blog post). <section> is for thematically grouping related content together.","C. <section> is older","D. <article> is only for text"],ans:1,exp:"You could have multiple <section>s inside a single <article>, or multiple <article>s inside a <section>."},
      {q:"Is a <div> tag semantic?",opts:["A. Yes, it means 'Division'","B. No, a <div> is purely a non-semantic container used for styling or layout grouping. It conveys absolutely zero meaning about its contents.","C. Only in HTML5","D. Yes, for screen readers"],ans:1,exp:"Use <div> when no other semantic tag fits the purpose."}
    ],
    flows:[
      {title:"Semantic Layout",items:["start:<body>","proc:<header> Logo & <nav> Links","proc:<main> Core Content","dec:<article> Blog Post","proc:<aside> Sidebar Ads","end:<footer> Copyright Info"]}
    ],
    game:{icon:"🏗️",title:"The Structurer",desc:"Master HTML semantics",badges:["🏗️ Architect","🤖 SEO Bot","🗣️ Screen Reader"],challenges:[{icon:"📝",title:"Div Soup",desc:"Why is <div> everywhere bad?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Semantic Conversion",badge:"Refactorer",desc:"Change div soup to semantic HTML.",tags:["HTML","Frontend"],steps:[{title:"Bad Code",desc:"<div class='header'> <div class='main-content'>"},{"title:"Refactor",desc:"Change to <header> and <main>"},{"title:"Result",desc:"Screen readers can now navigate instantly."}],code:`<!-- BAD (Div Soup) -->\n<div class="header">My Blog</div>\n<div class="content">\n  <div class="post">Hello World</div>\n</div>\n\n<!-- GOOD (Semantic) -->\n<header>My Blog</header>\n<main>\n  <article>Hello World</article>\n</main>`}
  },
  t102: {
    tag:'Phase 3 · Frontend', num:102,
    title:'CSS Box Model',
    desc:'The foundation of all web layout, defining how elements take up space.',
    theory:`<div class="card"><h3>📦 The Invisible Boxes</h3><p>Everything on a web page is a rectangular box. The <strong>CSS Box Model</strong> dictates how the size of that box is calculated.</p><h4>The 4 Layers (from inside to outside)</h4><ol><li><strong>Content:</strong> The actual text or image. Width and height apply here by default.</li><li><strong>Padding:</strong> Transparent space <em>inside</em> the box, between the content and the border. (Background color applies to padding).</li><li><strong>Border:</strong> A line wrapping around the padding.</li><li><strong>Margin:</strong> Transparent space <em>outside</em> the box, pushing other elements away.</li></ol><div class="box b-vi"><h5>The box-sizing Hack</h5><p>By default, if you set <code>width: 100px; padding: 20px;</code>, the total width becomes 140px! Setting <code>box-sizing: border-box;</code> forces the padding and border to shrink <em>inward</em>, keeping the total width locked at 100px.</p></div></div>`,
    mcqs:[
      {q:"In the CSS Box Model, what is the space INSIDE the border, between the border and the actual text content?",opts:["A. Margin","B. Padding","C. Outline","D. Gutter"],ans:1,exp:"Padding puffs the box up from the inside."},
      {q:"What is Margin?",opts:["A. Space inside the box","B. The thickness of the box's wall","C. Invisible space OUTSIDE the border that pushes other elements away","D. The width of the text"],ans:2,exp:"Margins do not have background colors; they are always transparent."},
      {q:"If a div has width: 200px, padding: 10px, and border: 5px (using the default box-sizing: content-box), what is the total visible width of the element?",opts:["A. 200px","B. 210px","C. 230px","D. 215px"],ans:2,exp:"200 (content) + 10 (left pad) + 10 (right pad) + 5 (left border) + 5 (right border) = 230px."},
      {q:"What CSS property completely fixes the annoying math of the default Box Model, ensuring that a 200px width element stays exactly 200px wide regardless of padding?",opts:["A. width-lock: true","B. box-sizing: border-box","C. padding-style: internal","D. display: flex"],ans:1,exp:"border-box is so universally loved that almost every modern website applies it globally using the '*' selector."},
      {q:"Does a background-color apply to the Margin area?",opts:["A. Yes","B. No, background-color only fills the Content and Padding areas. Margins are completely transparent.","C. Only on Chrome","D. Yes, if you use !important"],ans:1,exp:"This is why we use Padding to make a colored button bigger, not Margin."}
    ],
    flows:[
      {title:"Box Model Layers",items:["start:Content (Text/Image)","proc:Padding (Inner Space)","proc:Border (The Wall)","end:Margin (Outer Space)"]}
    ],
    game:{icon:"📦",title:"The Packer",desc:"Master the Box Model",badges:["📦 Box Sizer","📏 Padding Pro","🚧 Border Guard"],challenges:[{icon:"📝",title:"Math Problem",desc:"Calculate total width",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Global Reset",badge:"Resetter",desc:"Apply the ultimate CSS box-sizing reset.",tags:["CSS","Layout"],steps:[{title:"Selector",desc:"Use the Universal Selector (*) "},{"title:"Property",desc:"box-sizing: border-box"},{"title:"Result",desc:"Padding no longer breaks your layout widths!"}],code:`/* The most important CSS snippet you will ever write. */\n/* Applies to all elements, and all before/after pseudo-elements */\n*, *::before, *::after {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\n\n/* Now, a 50% width div with 50px padding stays EXACTLY 50% wide! */`}
  },
  t103: {
    tag:'Phase 3 · Frontend', num:103,
    title:'Flexbox vs Grid',
    desc:'Modern CSS layout systems for creating complex, responsive designs without floats.',
    theory:`<div class="card"><h3>📐 1D vs 2D Layouts</h3><p>Before Flexbox, developers used awful hacks (like <code>float: left</code> and clearing floats) to align items side-by-side.</p><h4>Flexbox (1-Dimensional)</h4><p>Use Flexbox when you want to lay items out in a <strong>single line</strong> (either a row OR a column). It is incredible for alignment, centering, and distributing space dynamically (e.g., a Navigation bar).</p><h4>CSS Grid (2-Dimensional)</h4><p>Use Grid when you need to layout items in <strong>both rows AND columns simultaneously</strong>. It allows you to create complex page architectures (e.g., Header on top, Sidebar on left, Content in middle, Footer on bottom) with ease.</p></div>`,
    mcqs:[
      {q:"What is the primary difference between CSS Flexbox and CSS Grid?",opts:["A. Flexbox is older","B. Flexbox is 1-Dimensional (deals with either rows OR columns). Grid is 2-Dimensional (deals with rows AND columns simultaneously).","C. Grid is for mobile, Flexbox is for desktop","D. Flexbox is Javascript"],ans:1,exp:"You use Grid for the macro layout of the page, and Flexbox for the micro layout of components inside the grid cells."},
      {q:"How do you perfectly center a div horizontally AND vertically using Flexbox?",opts:["A. margin: auto","B. display: flex; justify-content: center; align-items: center;","C. text-align: center; vertical-align: middle;","D. float: center"],ans:1,exp:"This 3-line snippet solved a problem that plagued web developers for 15 years."},
      {q:"In Flexbox, what does 'justify-content: space-between' do?",opts:["A. It adds a background color","B. It pushes the first item to the far left, the last item to the far right, and evenly spaces the remaining items in between","C. It stacks them vertically","D. It wraps them to the next line"],ans:1,exp:"This is the standard way to build a Nav bar (Logo on left, Links on right)."},
      {q:"What CSS Grid property allows a child element to span across multiple columns?",opts:["A. flex-grow: 3","B. grid-column: span 3; (or grid-column: 1 / 4)","C. width: 300%","D. column-count: 3"],ans:1,exp:"Grid allows items to break out of single cells and span massive areas of the template."},
      {q:"Can you use Flexbox inside of a CSS Grid?",opts:["A. Yes, absolutely. It is highly recommended.","B. No, they conflict and crash the browser","C. Only in Safari","D. Only if you use !important"],ans:0,exp:"Grid for the whole page layout. Flexbox inside the Header to align the links."}
    ],
    flows:[
      {title:"Choosing a Layout",items:["start:Need complex 2D architecture?","dec:(Yes) Use CSS Grid (Columns & Rows)","proc:(No) Just a single row of buttons?","end:Use Flexbox (justify-content, align-items)"]}
    ],
    game:{icon:"📐",title:"The Aligner",desc:"Master modern layouts",badges:["📐 Grid Architect","🤸 Flex Gymnast","🎯 Perfect Center"],challenges:[{icon:"📝",title:"Center Div",desc:"Write the 3 lines to center a div",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Holy Grail Layout",badge:"Holy Grail",desc:"Build the classic layout with Grid.",tags:["CSS","Grid"],steps:[{title:"Container",desc:"display: grid; grid-template-columns: 200px 1fr;"},{"title:"Rows",desc:"grid-template-rows: auto 1fr auto;"},{"title:"Span",desc:"Make Header and Footer span 2 columns"}],code:`/* The Holy Grail Layout (Header, Sidebar, Main, Footer) */\n.container {\n  display: grid;\n  grid-template-columns: 250px 1fr; /* Sidebar, Main */\n  grid-template-rows: 60px 1fr 60px; /* Header, Body, Footer */\n}\n\n.header {\n  grid-column: 1 / -1; /* Spans across all columns from left to right! */\n}\n.footer {\n  grid-column: 1 / -1;\n}`}
  },
  t104: {
    tag:'Phase 3 · Frontend', num:104,
    title:'CSS Variables & Theming',
    desc:'Custom properties that allow you to store and reuse values across your stylesheets.',
    theory:`<div class="card"><h3>🎨 The Theme Engine</h3><p>Before CSS Variables, if your brand color was <code>#ff0055</code>, you had to copy/paste that exact hex code 500 times across your CSS file. If the brand color changed, you had to do a massive Find & Replace.</p><h4>Custom Properties (Variables)</h4><p>You can define variables on the <code>:root</code> selector (the HTML tag), making them globally accessible. You reference them using the <code>var()</code> function.</p><div class="box b-am"><h5>Dark Mode Magic</h5><p>Because CSS Variables are read at runtime by the browser (unlike SASS variables), you can instantly swap them out using a single line of JavaScript or a media query to create a Dark Mode!</p></div></div>`,
    mcqs:[
      {q:"How do you declare a CSS variable (Custom Property)?",opts:["A. $primary-color: blue;","B. --primary-color: blue;","C. var primary-color = blue;","D. @primary-color: blue;"],ans:1,exp:"CSS variables always start with two dashes (--)."},
      {q:"How do you use a CSS variable in your code?",opts:["A. color: --primary-color;","B. color: var(--primary-color);","C. color: $primary-color;","D. color: get(--primary-color);"],ans:1,exp:"You must wrap the variable name in the var() function."},
      {q:"Why are native CSS variables better than SASS/LESS variables?",opts:["A. They are faster","B. CSS variables exist in the DOM at runtime. You can change them dynamically with JavaScript or CSS Media Queries (e.g., swapping a light theme for a dark theme instantly). SASS variables are compiled away and don't exist in the browser.","C. They use less memory","D. They are older"],ans:1,exp:"This runtime flexibility is the foundation of modern dark modes."},
      {q:"Where should you define CSS variables if you want them to be accessible globally across the entire website?",opts:["A. Inside the body tag","B. Inside the :root pseudo-class","C. Inside the header tag","D. Inside a JavaScript file"],ans:1,exp:":root targets the highest level <html> element, making the variables cascade down to everything."},
      {q:"What is the second argument in the var() function used for? (e.g., var(--brand, red))",opts:["A. To declare the variable","B. It is a Fallback value. If '--brand' is not defined or is invalid, the browser will use 'red' instead.","C. To multiply the color","D. To animate the color"],ans:1,exp:"Fallbacks are great for building robust, reusable component libraries."}
    ],
    flows:[
      {title:"Dark Mode Toggle",items:["start::root { --bg: white; --text: black; }","proc:JS: document.body.classList.add('dark')","dec:.dark { --bg: black; --text: white; }","end:All components using var(--bg) instantly change colors!"]}
    ],
    game:{icon:"🎨",title:"The Artist",desc:"Master CSS Variables",badges:["🎨 Theme Maker","🌙 Dark Moder","📦 Fallback Provider"],challenges:[{icon:"📝",title:"Syntax",desc:"Write a valid CSS variable declaration",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Dark Mode Engine",badge:"Night Owl",desc:"Implement a CSS variable dark mode.",tags:["CSS","Theming"],steps:[{title:"Light Theme",desc:":root { --bg: #fff; --text: #000; }"},{"title:"Dark Theme",desc:"[data-theme='dark'] { --bg: #000; --text: #fff; }"},{"title:"Apply",desc:"body { background: var(--bg); color: var(--text); }"}],code:`/* The modern way to build themes */\n\n:root {\n  --surface: #ffffff;\n  --text: #111111;\n}\n\n/* When JS adds data-theme="dark" to the <body> tag, these values overwrite the root! */\n[data-theme="dark"] {\n  --surface: #121212;\n  --text: #eeeeee;\n}\n\nbody {\n  background-color: var(--surface);\n  color: var(--text);\n  transition: background-color 0.3s ease;\n}`}
  },
  t105: {
    tag:'Phase 3 · Frontend', num:105,
    title:'Responsive Design',
    desc:'Ensuring websites look perfect on any screen size, from a 4-inch phone to a 4k monitor.',
    theory:`<div class="card"><h3>📱 Fluid Layouts</h3><p>In the past, companies built two separate websites (m.example.com for mobile, www for desktop). <strong>Responsive Web Design (RWD)</strong> allows a single HTML codebase to dynamically adapt to the user's screen size.</p><h4>Media Queries</h4><p>The core of RWD is the <code>@media</code> rule. It allows you to apply specific CSS rules ONLY if a certain condition is met (like the screen width being smaller than 768px).</p><h4>Mobile First Approach</h4><p>Best practice is to write your default CSS for mobile phones first. Then, use <code>min-width</code> media queries to progressively add complexity and columns as the screen gets wider.</p></div>`,
    mcqs:[
      {q:"What is the purpose of a CSS Media Query?",opts:["A. To play video files","B. To apply CSS rules conditionally based on the device's characteristics (like screen width, orientation, or print mode)","C. To query a database","D. To load JavaScript"],ans:1,exp:"Media queries act like 'IF' statements for your CSS."},
      {q:"What does the 'Mobile First' design philosophy mean?",opts:["A. You only build a mobile app","B. You write the default CSS for mobile screens first (no media queries). Then you use @media (min-width: 768px) to add desktop styles as the screen grows.","C. You write desktop first, then shrink it","D. You use a mobile database"],ans:1,exp:"Mobile layouts are usually simple (1 column). It is much easier to start simple and add complexity, rather than starting complex and trying to strip it away."},
      {q:"Which HTML meta tag is absolutely MANDATORY for responsive design to work on mobile devices?",opts:["A. <meta charset='UTF-8'>","B. <meta name='viewport' content='width=device-width, initial-scale=1.0'>","C. <meta name='description'>","D. <title>"],ans:1,exp:"Without the viewport tag, a mobile phone will assume your site is a desktop site and zoom way out, making text unreadable."},
      {q:"If you want a rule to apply ONLY to screens that are 600px wide or SMALLER, which media query do you use?",opts:["A. @media (min-width: 600px)","B. @media (max-width: 600px)","C. @media (width == 600px)","D. @media (mobile)"],ans:1,exp:"max-width means 'Apply these rules up to a maximum width of 600px'."},
      {q:"Which CSS unit is Relative to the font-size of the root <html> element, making it ideal for responsive typography?",opts:["A. px (Pixels)","B. rem (Root EM)","C. cm (Centimeters)","D. pt (Points)"],ans:1,exp:"If you use 'rem', and a visually impaired user increases their browser's default font size, your entire layout will scale up beautifully to accommodate them."}
    ],
    flows:[
      {title:"Mobile First Progression",items:["start:Default CSS: grid-template-columns: 1fr (Mobile)","dec:Screen hits 768px (Tablet)","proc:@media(min-width:768px) { grid-columns: 1fr 1fr }","dec:Screen hits 1024px (Desktop)","end:@media(min-width:1024px) { grid-columns: 1fr 1fr 1fr }"]}
    ],
    game:{icon:"📱",title:"The Resizer",desc:"Master fluid layouts",badges:["📱 Mobile First","📏 Viewport Meta","🖋️ REM Typer"],challenges:[{icon:"📝",title:"Min vs Max",desc:"When to use min-width vs max-width?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Responsive Grid",badge:"Fluidity",desc:"Build a grid that goes from 1 to 3 columns.",tags:["CSS","Responsive"],steps:[{title:"Mobile",desc:"Default to 1 column: display: grid; grid-columns: 1fr;"},{"title:"Tablet",desc:"@media (min-width: 768px): change to 2fr;"},{"title:"Desktop",desc:"@media (min-width: 1024px): change to 3fr;"}],code:`/* 1. Mobile First Default (1 Column) */\n.gallery {\n  display: grid;\n  grid-template-columns: 1fr;\n}\n\n/* 2. Tablet (2 Columns) */\n@media (min-width: 768px) {\n  .gallery {\n    grid-template-columns: 1fr 1fr;\n  }\n}\n\n/* 3. Desktop (4 Columns) */\n@media (min-width: 1024px) {\n  .gallery {\n    grid-template-columns: repeat(4, 1fr);\n  }\n}`}
  },
  t106: {
    tag:'Phase 3 · Frontend', num:106,
    title:'DOM Manipulation',
    desc:'Using JavaScript to dynamically read, create, update, and delete HTML elements on the page.',
    theory:`<div class="card"><h3>🌳 The Document Tree</h3><p>When the browser loads your HTML file, it converts it into a Javascript Object called the <strong>Document Object Model (DOM)</strong>. It is a tree-like structure where every tag (div, p, h1) is a "Node".</p><h4>Selecting and Modifying</h4><p>Using the global <code>document</code> object, you can select any node using <code>querySelector()</code>. Once selected, you can change its text (<code>innerText</code>), change its CSS classes (<code>classList.add()</code>), or even inject entirely new HTML (<code>innerHTML</code>) dynamically without refreshing the page.</p></div>`,
    mcqs:[
      {q:"What does DOM stand for?",opts:["A. Data Object Model","B. Document Object Model","C. Dynamic Output Module","D. Display Oriented Markup"],ans:1,exp:"It is an object-oriented representation of the web page."},
      {q:"What is the most versatile and modern JavaScript method for selecting an element from the DOM?",opts:["A. document.getElementById()","B. document.querySelector()","C. document.getElementsByTagName()","D. document.find()"],ans:1,exp:"querySelector() allows you to use standard CSS selectors (like '.class' or '#id' or 'div > p') to find elements."},
      {q:"If you select a button element, how do you make it react to a user clicking on it?",opts:["A. button.onClick = true;","B. button.addEventListener('click', function() { ... });","C. button.listen()","D. button.click()"],ans:1,exp:"Event listeners wait in the background for a specific event to occur on the target element."},
      {q:"What is the difference between innerText and innerHTML?",opts:["A. They are exactly the same","B. innerText safely treats everything as pure text. innerHTML parses the string as actual HTML, allowing you to inject bold tags or new divs.","C. innerHTML is for CSS","D. innerText is faster"],ans:1,exp:"WARNING: Using innerHTML with user-submitted data creates a massive security flaw called XSS (Cross-Site Scripting). Always use innerText or textContent for user input."},
      {q:"How do you dynamically create a brand new HTML element using JavaScript?",opts:["A. document.createElement('div')","B. document.newElement('div')","C. document.add('div')","D. document.make('div')"],ans:0,exp:"Once created, you must use appendChild() to actually attach it to the DOM tree so it becomes visible."}
    ],
    flows:[
      {title:"Dynamic Creation",items:["start:let btn = document.createElement('button')","proc:btn.innerText = 'Click Me!'","proc:btn.classList.add('primary')","dec:document.body.appendChild(btn)","end:Button appears on screen!"]}
    ],
    game:{icon:"🌳",title:"The Tree Climber",desc:"Master the DOM",badges:["🌳 Node Navigator","🖱️ Listener","⚠️ XSS Aware"],challenges:[{icon:"📝",title:"querySelector",desc:"Select a div with class 'card'",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Dark Mode Toggle JS",badge:"Interactive",desc:"Use JS to toggle a class on the body.",tags:["JavaScript","DOM"],steps:[{title:"Select",desc:"const btn = document.querySelector('#theme-btn')"},{"title:"Listen",desc:"btn.addEventListener('click', () => { ... })"},{"title:"Modify",desc:"document.body.classList.toggle('dark-mode')"}],code:`// Grab the button\nconst btn = document.querySelector('#theme-btn');\n\n// Add interactivity\nbtn.addEventListener('click', () => {\n  // .toggle() adds the class if it's missing, or removes it if it's there!\n  document.body.classList.toggle('dark-mode');\n  \n  if (document.body.classList.contains('dark-mode')) {\n    btn.innerText = "Switch to Light";\n  } else {\n    btn.innerText = "Switch to Dark";\n  }\n});`}
  },
  t107: {
    tag:'Phase 3 · Frontend', num:107,
    title:'Event Bubbling & Capturing',
    desc:'How JavaScript handles events when elements are nested inside each other.',
    theory:`<div class="card"><h3>🫧 The Ripple Effect</h3><p>If you click on a <code>&lt;button&gt;</code> that is inside a <code>&lt;div&gt;</code> that is inside the <code>&lt;body&gt;</code>... you didn't just click the button. Technically, you clicked ALL of them. So which event fires first?</p><h4>Bubbling (Default)</h4><p>By default, JavaScript uses <strong>Event Bubbling</strong>. The event starts at the deepest target element (the Button), triggers its click listener, and then "bubbles up" to the Div, and then up to the Body, triggering their click listeners in sequence.</p><h4>Event Delegation</h4><p>Because of bubbling, if you have a list of 1000 items, you don't need to add 1000 event listeners. You add ONE listener to the parent <code>&lt;ul&gt;</code>. When an <code>&lt;li&gt;</code> is clicked, the event bubbles up to the <code>&lt;ul&gt;</code> where you handle it! This saves massive amounts of memory.</p></div>`,
    mcqs:[
      {q:"What is Event Bubbling?",opts:["A. The UI animation when clicking","B. An event starts at the target element and propagates UPWARD through its ancestors in the DOM tree, triggering their event listeners.","C. An event travels downward","D. A memory leak"],ans:1,exp:"Like a bubble rising in a glass of water, from the bottom (child) to the top (parent)."},
      {q:"If you have a click listener on a Button, and a click listener on its parent Div, and you click the Button... what happens by default?",opts:["A. Only the Button listener fires","B. Only the Div listener fires","C. The Button listener fires first, then the Div listener fires","D. The Div listener fires first, then the Button listener"],ans:2,exp:"This is Event Bubbling in action."},
      {q:"How can you STOP an event from bubbling up to parent elements?",opts:["A. return false;","B. Call event.stopPropagation() inside the child's event listener","C. event.preventDefault()","D. event.stop()"],ans:1,exp:"This stops the bubble from rising any further, protecting parent elements from accidental triggers."},
      {q:"What does event.preventDefault() do?",opts:["A. Stops bubbling","B. Prevents the browser's default behavior for that element (e.g., stopping a <form> from submitting and refreshing the page, or stopping a link from navigating away).","C. Deletes the element","D. Refreshes the page"],ans:1,exp:"This is absolutely critical in Single Page Applications (SPAs) like React where you want Javascript to handle form submissions without page reloads."},
      {q:"What is 'Event Delegation'?",opts:["A. Giving the event to a Web Worker","B. Taking advantage of bubbling by placing a single event listener on a Parent element to manage all clicks for its numerous Child elements.","C. Deleting events","D. Passing events to a database"],ans:1,exp:"Event delegation is a massive performance optimization for large lists or tables."}
    ],
    flows:[
      {title:"Event Delegation Flow",items:["start:User clicks <li>Item 500</li>","proc:<li> has NO listener. Event Bubbles UP!","dec:Hits parent <ul> which HAS a listener","proc:Listener checks event.target","end:Sees 'Item 500' was clicked. Handles it!"]}
    ],
    game:{icon:"🫧",title:"The Bubbler",desc:"Master event propagation",badges:["🫧 Bubble Rider","🛑 Propagator Stopper","🛡️ Delegator"],challenges:[{icon:"📝",title:"Default vs Propagation",desc:"Difference between preventDefault and stopPropagation?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Event Delegation",badge:"Optimizer",desc:"Handle 100 buttons with 1 listener.",tags:["JavaScript","Events"],steps:[{title:"Parent",desc:"<ul id='list'> with 100 <li> items inside"},{"title:"Listener",desc:"list.addEventListener('click', (e) => { ... })"},{"title:"Target",desc:"if(e.target.tagName === 'LI') console.log('Clicked!')"}],code:`const list = document.querySelector('#todo-list');\n\n// We attach ONE listener to the Parent (ul)\nlist.addEventListener('click', (event) => {\n  \n  // Check if what actually triggered the event (the target) was an li\n  if (event.target.tagName === 'LI') {\n    // We successfully delegated the event!\n    event.target.classList.toggle('completed');\n  }\n  \n});`}
  },
  t108: {
    tag:'Phase 3 · Frontend', num:108,
    title:'JavaScript ES6+ Features',
    desc:'Modern Javascript syntax updates that drastically improved developer experience.',
    theory:`<div class="card"><h3>✨ Modern JavaScript</h3><p>In 2015, JavaScript received a massive update called ES6 (ECMAScript 2015). It transformed JS from a clunky scripting language into a robust modern language. If you write React, you use ES6+ constantly.</p><h4>Key Features</h4><ul><li><strong>let & const:</strong> Replaced the buggy <code>var</code> keyword with Block-Scoped variables.</li><li><strong>Arrow Functions:</strong> <code>() => {}</code> shorter syntax and fixes the <code>this</code> context binding.</li><li><strong>Destructuring:</strong> Instantly extract values from Objects or Arrays. <code>const { name, age } = user;</code></li><li><strong>Spread Operator (...):</strong> Easily copy or merge objects and arrays. <code>const newObj = { ...oldObj, newField: 1 };</code></li><li><strong>Template Literals:</strong> String interpolation using backticks. <code>\`Hello ${name}\`</code></li></ul></div>`,
    mcqs:[
      {q:"Why should you always use 'let' or 'const' instead of 'var'?",opts:["A. 'var' is slower","B. 'let' and 'const' are Block-Scoped (they stay inside their {} brackets). 'var' is Function-Scoped and 'hoisted', leading to unpredictable bugs and memory leaks.","C. 'let' is for numbers, 'var' is for strings","D. They are identical"],ans:1,exp:"'var' is completely obsolete in modern JavaScript."},
      {q:"What does 'const' actually mean in JavaScript?",opts:["A. The value can never change","B. The variable identifier cannot be REASSIGNED to a completely new value. However, if it's an Object or Array, you CAN still mutate its internal contents (e.g., array.push()).","C. It stands for Constant Type","D. It acts as a global variable"],ans:1,exp:"const prevents reassignment, NOT mutation. To prevent mutation, you need Object.freeze()."},
      {q:"What does the Spread Operator (...) do in the following code: const b = [...a];",opts:["A. It crashes the program","B. It creates a brand new Array 'b' and copies all elements from Array 'a' into it (A shallow copy)","C. It multiplies the array","D. It deletes the array"],ans:1,exp:"Spread is heavily used in React and Redux to create new, immutable copies of state."},
      {q:"What is Object Destructuring?",opts:["A. Deleting an object","B. A syntax that allows you to unpack properties from objects into distinct variables: const { name } = user;","C. Merging two objects","D. Converting an object to JSON"],ans:1,exp:"It saves you from writing `const name = user.name; const age = user.age;` over and over."},
      {q:"What feature do Arrow Functions provide regarding the 'this' keyword?",opts:["A. They delete 'this'","B. They don't have their own 'this'. They inherit 'this' from the surrounding lexical scope, preventing annoying context bugs in callbacks.","C. They make 'this' global","D. They bind 'this' to the Window object"],ans:1,exp:"This is why we use Arrow Functions almost exclusively in modern React."}
    ],
    flows:[
      {title:"Destructuring & Spread",items:["start:const user = {id:1, name:'Bhoomi'}","proc:const { name } = user; (Extracts 'Bhoomi')","dec:const updatedUser = { ...user, age: 25 }","end:Result: {id:1, name:'Bhoomi', age:25}"]}
    ],
    game:{icon:"✨",title:"The Modernist",desc:"Master ES6+ syntax",badges:["✨ ES6 Expert","🏹 Arrow Shooter","📦 Destructurer"],challenges:[{icon:"📝",title:"let vs const",desc:"When should you use let?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"ES6 Refactor",badge:"Refactorer",desc:"Update old JS to modern ES6.",tags:["JavaScript","ES6"],steps:[{title:"Old",desc:"var name = user.name; var str = 'Hi ' + name;"},{"title:"Destructure",desc:"const { name } = user;"},{"title:"Template Literal",desc:"const str = `Hi ${name}`;"}],code:`const user = { name: "Bhoomi", age: 25, city: "Mumbai" };\n\n// 1. Destructuring\nconst { name, city } = user;\n\n// 2. Template Literals (Backticks)\nconst greeting = \`Welcome ${name} from ${city}!\`;\n\n// 3. Arrow Functions\nconst getGreeting = () => \`Welcome ${name}!\`;`}
  },
  t109: {
    tag:'Phase 3 · Frontend', num:109,
    title:'Promises & Async/Await',
    desc:'Handling asynchronous operations like fetching data from a server without freezing the browser.',
    theory:`<div class="card"><h3>⏳ Waiting for Data</h3><p>JavaScript is Single-Threaded. If you request data from a database and it takes 3 seconds, the entire browser would normally freeze. To solve this, JS uses <strong>Asynchronous Programming</strong>.</p><h4>Promises</h4><p>A Promise is an object representing the eventual completion (or failure) of an async operation. It has 3 states: <em>Pending</em>, <em>Fulfilled</em> (Resolved), or <em>Rejected</em>.</p><h4>Async / Await</h4><p>Introduced in ES8, <code>async/await</code> is syntactic sugar on top of Promises. Instead of chaining messy <code>.then()</code> blocks, you just put <code>await</code> in front of the Promise. It pauses the function execution until the data arrives, making async code look exactly like synchronous code!</p></div>`,
    mcqs:[
      {q:"Why is asynchronous programming necessary in JavaScript in the browser?",opts:["A. To make math faster","B. Because JS runs on a single thread. If a network request blocks that thread, the entire UI freezes and the user cannot click or scroll.","C. To encrypt data","D. To compile the code"],ans:1,exp:"Async allows the browser to send a request, continue rendering the UI, and deal with the response later when it arrives."},
      {q:"What are the three states of a Promise?",opts:["A. Start, Middle, End","B. Pending, Fulfilled (Resolved), Rejected","C. Sent, Received, Error","D. True, False, Null"],ans:1,exp:"You use .then() to handle a Fulfilled promise, and .catch() to handle a Rejected promise."},
      {q:"What is 'Callback Hell' (Pyramid of Doom)?",opts:["A. A server crash","B. Deeply nested callback functions used to handle sequential async operations in old Javascript, resulting in messy, unreadable code. Promises/Async-Await fixed this.","C. A database error","D. An infinite loop"],ans:1,exp:"Async/Await flattens the pyramid into clean, vertical lines of code."},
      {q:"What happens when you put the 'await' keyword in front of a function that returns a Promise?",opts:["A. The entire browser pauses","B. The execution of that specific 'async' function pauses until the Promise resolves, while the rest of the app continues running perfectly fine.","C. It deletes the promise","D. It triggers an error"],ans:1,exp:"You can ONLY use the 'await' keyword inside a function marked with 'async'."},
      {q:"How do you handle errors when using async/await?",opts:["A. Using a .catch() block","B. By wrapping the await calls in a standard try / catch block","C. You can't handle errors","D. Using an if statement"],ans:1,exp:"try/catch makes error handling look just like standard synchronous Java/C#."}
    ],
    flows:[
      {title:"Async / Await Flow",items:["start:Call async getProfile()","proc:await fetch('/api/user')","dec:Browser continues rendering UI while waiting!","proc:(3 secs later) Data arrives!","end:Function resumes, updates DOM with User name"]}
    ],
    game:{icon:"⏳",title:"The Timekeeper",desc:"Master async Javascript",badges:["⏳ Promise Keeper","⏱️ Awaiter","🛑 Catch Block"],challenges:[{icon:"📝",title:"The 3 States",desc:"Name the 3 Promise states",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Fetch User API",badge:"Networker",desc:"Use async/await to fetch data.",tags:["JavaScript","Async"],steps:[{title:"Async Func",desc:"async function loadUser()"},{"title:"Await Fetch",desc:"const res = await fetch('https://api.github.com/users/octocat')"},{"title:"Await JSON",desc:"const data = await res.json(); console.log(data);"}],code:`// Clean, modern Async/Await data fetching\nasync function fetchGitHubProfile() {\n  try {\n    // 1. Await the network request\n    const response = await fetch('https://api.github.com/users/bhoomi');\n    \n    // 2. Await the JSON parsing\n    const data = await response.json();\n    \n    console.log("Profile Name:", data.name);\n  } catch (error) {\n    // 3. Handle network failures gracefully\n    console.error("Failed to fetch data:", error);\n  }\n}`}
  },
  t110: {
    tag:'Phase 3 · Frontend', num:110,
    title:'Web APIs (Fetch, Storage)',
    desc:'Native browser tools for networking and storing data locally on the user device.',
    theory:`<div class="card"><h3>🌐 Browser Superpowers</h3><p>The browser provides powerful built-in APIs that your JavaScript can interact with.</p><h4>The Fetch API</h4><p>The modern, Promise-based way to make HTTP requests (GET, POST, PUT, DELETE) to external servers. It completely replaces the old, clunky <code>XMLHttpRequest (AJAX)</code>.</p><h4>Web Storage API</h4><p>Allows you to store Key-Value pairs directly in the user's browser.</p><ul><li><strong>localStorage:</strong> Persists data forever (until manually cleared). Great for saving dark-mode preferences or auth tokens.</li><li><strong>sessionStorage:</strong> Persists data only until the browser tab is closed.</li></ul></div>`,
    mcqs:[
      {q:"What is the Fetch API used for?",opts:["A. Downloading images","B. Making asynchronous network requests (HTTP) to servers to retrieve or send data (usually JSON)","C. Fetching data from the hard drive","D. Animating elements"],ans:1,exp:"Fetch is built into every modern browser natively; you don't need external libraries like Axios for basic requests."},
      {q:"By default, what HTTP method does the fetch() function use if you don't specify one?",opts:["A. POST","B. PUT","C. GET","D. DELETE"],ans:2,exp:"fetch('url') is automatically a GET request."},
      {q:"What is the difference between localStorage and sessionStorage?",opts:["A. localStorage stores 5MB, sessionStorage stores 10MB","B. localStorage persists data even if the browser is closed and reopened. sessionStorage deletes the data as soon as the tab is closed.","C. localStorage is for strings, session for arrays","D. There is no difference"],ans:1,exp:"Use localStorage for a 'Remember Me' feature. Use sessionStorage for a multi-page checkout process."},
      {q:"What data types can you store in localStorage?",opts:["A. Objects and Arrays","B. ONLY Strings. You must use JSON.stringify() to store an object, and JSON.parse() to read it back out.","C. Integers","D. Binary data"],ans:1,exp:"If you try to store an object directly, localStorage will literally just save the useless string '[object Object]'."},
      {q:"Why should you NEVER store sensitive data (like unencrypted passwords or credit cards) in localStorage?",opts:["A. It takes up too much space","B. Because it is vulnerable to XSS (Cross-Site Scripting) attacks. Any malicious Javascript running on the page can easily read localStorage and steal the data.","C. The browser deletes it randomly","D. It causes the browser to crash"],ans:1,exp:"Store secure Auth tokens in HTTPOnly Cookies, not localStorage."}
    ],
    flows:[
      {title:"LocalStorage JSON Flow",items:["start:const user = { name: 'Bhoomi' }","proc:localStorage.setItem('user', JSON.stringify(user))","dec:User reloads page next day","proc:const raw = localStorage.getItem('user')","end:const parsed = JSON.parse(raw). Ready!"]}
    ],
    game:{icon:"🌐",title:"The Webmaster",desc:"Master browser APIs",badges:["🌐 Fetcher","💾 Local Storer","🔐 XSS Cautious"],challenges:[{icon:"📝",title:"JSON Parse",desc:"Why use JSON.stringify for localStorage?",xp:50},{icon:"⚡",title:"MCQ Master",desc:"Score 5/5 on MCQs",xp:100}]},
    project:{title:"Theme Saver",badge:"Persister",desc:"Save a user's theme preference to localStorage.",tags:["JavaScript","Storage"],steps:[{title:"Save",desc:"localStorage.setItem('theme', 'dark')"},{"title:"Load",desc:"const theme = localStorage.getItem('theme')"},{"title:"Apply",desc:"If theme === 'dark', apply dark mode on page load."}],code:`// Save preference when user clicks the toggle\nfunction saveThemePref() {\n  localStorage.setItem("theme", "dark");\n}\n\n// Run this instantly when the page loads!\nfunction applySavedTheme() {\n  const savedTheme = localStorage.getItem("theme");\n  if (savedTheme === "dark") {\n    document.body.classList.add("dark-mode");\n  }\n}\n\napplySavedTheme();`}
  },
"""

start_marker = "};\n\nlet userXP"
inject_idx = content.find(start_marker)

if inject_idx != -1:
    new_content = content[:inject_idx] + ",\n" + rich_content + content[inject_idx:]
    with open(html_path, "w") as f:
        f.write(new_content)
    print("Successfully generated T101-T110 rich content!")
else:
    print("Could not find injection point.")
