name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - bhoomi

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # This is the new step! Log into the Docker Hub Registry using Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image and PUSH it to the registry
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bhoomi14092005/my-first-devops-api:latest

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Fake Deploy to AWS Staging
        run: echo "AWS is now downloading bhoomi14092005/my-first-devops-api:latest from Docker Hub!"

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Fake Deploy to AWS Production
        run: echo "DANGER! AWS is deploying bhoomi14092005/my-first-devops-api:latest to Live Servers!"
